// Code generated by mockery v2.53.6. DO NOT EDIT.

package types

import (
	mock "github.com/stretchr/testify/mock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockSetOwnerFunc is an autogenerated mock type for the SetOwnerFunc type
type MockSetOwnerFunc struct {
	mock.Mock
}

type MockSetOwnerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSetOwnerFunc) EXPECT() *MockSetOwnerFunc_Expecter {
	return &MockSetOwnerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: targetObject
func (_m *MockSetOwnerFunc) Execute(targetObject client.Object) error {
	ret := _m.Called(targetObject)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(client.Object) error); ok {
		r0 = rf(targetObject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSetOwnerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSetOwnerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - targetObject client.Object
func (_e *MockSetOwnerFunc_Expecter) Execute(targetObject interface{}) *MockSetOwnerFunc_Execute_Call {
	return &MockSetOwnerFunc_Execute_Call{Call: _e.mock.On("Execute", targetObject)}
}

func (_c *MockSetOwnerFunc_Execute_Call) Run(run func(targetObject client.Object)) *MockSetOwnerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.Object))
	})
	return _c
}

func (_c *MockSetOwnerFunc_Execute_Call) Return(_a0 error) *MockSetOwnerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSetOwnerFunc_Execute_Call) RunAndReturn(run func(client.Object) error) *MockSetOwnerFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSetOwnerFunc creates a new instance of MockSetOwnerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSetOwnerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSetOwnerFunc {
	mock := &MockSetOwnerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
