// Code generated by mockery v2.53.3. DO NOT EDIT.

package expose

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1alpha1 "github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/generated/applyconfiguration/traefikio/v1alpha1"
	traefikiov1alpha1 "github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/traefikio/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
)

// mockMiddlewareManager is an autogenerated mock type for the middlewareManager type
type mockMiddlewareManager struct {
	mock.Mock
}

type mockMiddlewareManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMiddlewareManager) EXPECT() *mockMiddlewareManager_Expecter {
	return &mockMiddlewareManager_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, middleware, opts
func (_m *mockMiddlewareManager) Apply(ctx context.Context, middleware *v1alpha1.MiddlewareApplyConfiguration, opts v1.ApplyOptions) (*traefikiov1alpha1.Middleware, error) {
	ret := _m.Called(ctx, middleware, opts)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *traefikiov1alpha1.Middleware
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.MiddlewareApplyConfiguration, v1.ApplyOptions) (*traefikiov1alpha1.Middleware, error)); ok {
		return rf(ctx, middleware, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.MiddlewareApplyConfiguration, v1.ApplyOptions) *traefikiov1alpha1.Middleware); ok {
		r0 = rf(ctx, middleware, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefikiov1alpha1.Middleware)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.MiddlewareApplyConfiguration, v1.ApplyOptions) error); ok {
		r1 = rf(ctx, middleware, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMiddlewareManager_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type mockMiddlewareManager_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - middleware *v1alpha1.MiddlewareApplyConfiguration
//   - opts v1.ApplyOptions
func (_e *mockMiddlewareManager_Expecter) Apply(ctx interface{}, middleware interface{}, opts interface{}) *mockMiddlewareManager_Apply_Call {
	return &mockMiddlewareManager_Apply_Call{Call: _e.mock.On("Apply", ctx, middleware, opts)}
}

func (_c *mockMiddlewareManager_Apply_Call) Run(run func(ctx context.Context, middleware *v1alpha1.MiddlewareApplyConfiguration, opts v1.ApplyOptions)) *mockMiddlewareManager_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.MiddlewareApplyConfiguration), args[2].(v1.ApplyOptions))
	})
	return _c
}

func (_c *mockMiddlewareManager_Apply_Call) Return(result *traefikiov1alpha1.Middleware, err error) *mockMiddlewareManager_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockMiddlewareManager_Apply_Call) RunAndReturn(run func(context.Context, *v1alpha1.MiddlewareApplyConfiguration, v1.ApplyOptions) (*traefikiov1alpha1.Middleware, error)) *mockMiddlewareManager_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, middleware, opts
func (_m *mockMiddlewareManager) Create(ctx context.Context, middleware *traefikiov1alpha1.Middleware, opts v1.CreateOptions) (*traefikiov1alpha1.Middleware, error) {
	ret := _m.Called(ctx, middleware, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *traefikiov1alpha1.Middleware
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *traefikiov1alpha1.Middleware, v1.CreateOptions) (*traefikiov1alpha1.Middleware, error)); ok {
		return rf(ctx, middleware, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *traefikiov1alpha1.Middleware, v1.CreateOptions) *traefikiov1alpha1.Middleware); ok {
		r0 = rf(ctx, middleware, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefikiov1alpha1.Middleware)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *traefikiov1alpha1.Middleware, v1.CreateOptions) error); ok {
		r1 = rf(ctx, middleware, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMiddlewareManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockMiddlewareManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - middleware *traefikiov1alpha1.Middleware
//   - opts v1.CreateOptions
func (_e *mockMiddlewareManager_Expecter) Create(ctx interface{}, middleware interface{}, opts interface{}) *mockMiddlewareManager_Create_Call {
	return &mockMiddlewareManager_Create_Call{Call: _e.mock.On("Create", ctx, middleware, opts)}
}

func (_c *mockMiddlewareManager_Create_Call) Run(run func(ctx context.Context, middleware *traefikiov1alpha1.Middleware, opts v1.CreateOptions)) *mockMiddlewareManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*traefikiov1alpha1.Middleware), args[2].(v1.CreateOptions))
	})
	return _c
}

func (_c *mockMiddlewareManager_Create_Call) Return(_a0 *traefikiov1alpha1.Middleware, _a1 error) *mockMiddlewareManager_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMiddlewareManager_Create_Call) RunAndReturn(run func(context.Context, *traefikiov1alpha1.Middleware, v1.CreateOptions) (*traefikiov1alpha1.Middleware, error)) *mockMiddlewareManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdateAlternativeFQDNRedirectMiddleware provides a mock function with given fields: ctx, alternativeFQDNs, primaryFQDN, ownerReferences
func (_m *mockMiddlewareManager) CreateOrUpdateAlternativeFQDNRedirectMiddleware(ctx context.Context, alternativeFQDNs []string, primaryFQDN string, ownerReferences []v1.OwnerReference) (string, error) {
	ret := _m.Called(ctx, alternativeFQDNs, primaryFQDN, ownerReferences)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateAlternativeFQDNRedirectMiddleware")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string, []v1.OwnerReference) (string, error)); ok {
		return rf(ctx, alternativeFQDNs, primaryFQDN, ownerReferences)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string, []v1.OwnerReference) string); ok {
		r0 = rf(ctx, alternativeFQDNs, primaryFQDN, ownerReferences)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string, []v1.OwnerReference) error); ok {
		r1 = rf(ctx, alternativeFQDNs, primaryFQDN, ownerReferences)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateAlternativeFQDNRedirectMiddleware'
type mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call struct {
	*mock.Call
}

// CreateOrUpdateAlternativeFQDNRedirectMiddleware is a helper method to define mock.On call
//   - ctx context.Context
//   - alternativeFQDNs []string
//   - primaryFQDN string
//   - ownerReferences []v1.OwnerReference
func (_e *mockMiddlewareManager_Expecter) CreateOrUpdateAlternativeFQDNRedirectMiddleware(ctx interface{}, alternativeFQDNs interface{}, primaryFQDN interface{}, ownerReferences interface{}) *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call {
	return &mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call{Call: _e.mock.On("CreateOrUpdateAlternativeFQDNRedirectMiddleware", ctx, alternativeFQDNs, primaryFQDN, ownerReferences)}
}

func (_c *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call) Run(run func(ctx context.Context, alternativeFQDNs []string, primaryFQDN string, ownerReferences []v1.OwnerReference)) *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string), args[3].([]v1.OwnerReference))
	})
	return _c
}

func (_c *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call) Return(_a0 string, _a1 error) *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call) RunAndReturn(run func(context.Context, []string, string, []v1.OwnerReference) (string, error)) *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *mockMiddlewareManager) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockMiddlewareManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockMiddlewareManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.DeleteOptions
func (_e *mockMiddlewareManager_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *mockMiddlewareManager_Delete_Call {
	return &mockMiddlewareManager_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockMiddlewareManager_Delete_Call) Run(run func(ctx context.Context, name string, opts v1.DeleteOptions)) *mockMiddlewareManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.DeleteOptions))
	})
	return _c
}

func (_c *mockMiddlewareManager_Delete_Call) Return(_a0 error) *mockMiddlewareManager_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMiddlewareManager_Delete_Call) RunAndReturn(run func(context.Context, string, v1.DeleteOptions) error) *mockMiddlewareManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *mockMiddlewareManager) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.DeleteOptions, v1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockMiddlewareManager_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type mockMiddlewareManager_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.DeleteOptions
//   - listOpts v1.ListOptions
func (_e *mockMiddlewareManager_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *mockMiddlewareManager_DeleteCollection_Call {
	return &mockMiddlewareManager_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *mockMiddlewareManager_DeleteCollection_Call) Run(run func(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions)) *mockMiddlewareManager_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.DeleteOptions), args[2].(v1.ListOptions))
	})
	return _c
}

func (_c *mockMiddlewareManager_DeleteCollection_Call) Return(_a0 error) *mockMiddlewareManager_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMiddlewareManager_DeleteCollection_Call) RunAndReturn(run func(context.Context, v1.DeleteOptions, v1.ListOptions) error) *mockMiddlewareManager_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockMiddlewareManager) Get(ctx context.Context, name string, opts v1.GetOptions) (*traefikiov1alpha1.Middleware, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *traefikiov1alpha1.Middleware
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*traefikiov1alpha1.Middleware, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *traefikiov1alpha1.Middleware); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefikiov1alpha1.Middleware)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMiddlewareManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockMiddlewareManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *mockMiddlewareManager_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockMiddlewareManager_Get_Call {
	return &mockMiddlewareManager_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockMiddlewareManager_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *mockMiddlewareManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *mockMiddlewareManager_Get_Call) Return(_a0 *traefikiov1alpha1.Middleware, _a1 error) *mockMiddlewareManager_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMiddlewareManager_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*traefikiov1alpha1.Middleware, error)) *mockMiddlewareManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *mockMiddlewareManager) List(ctx context.Context, opts v1.ListOptions) (*traefikiov1alpha1.MiddlewareList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *traefikiov1alpha1.MiddlewareList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*traefikiov1alpha1.MiddlewareList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *traefikiov1alpha1.MiddlewareList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefikiov1alpha1.MiddlewareList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMiddlewareManager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockMiddlewareManager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *mockMiddlewareManager_Expecter) List(ctx interface{}, opts interface{}) *mockMiddlewareManager_List_Call {
	return &mockMiddlewareManager_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *mockMiddlewareManager_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *mockMiddlewareManager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *mockMiddlewareManager_List_Call) Return(_a0 *traefikiov1alpha1.MiddlewareList, _a1 error) *mockMiddlewareManager_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMiddlewareManager_List_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (*traefikiov1alpha1.MiddlewareList, error)) *mockMiddlewareManager_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *mockMiddlewareManager) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (*traefikiov1alpha1.Middleware, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *traefikiov1alpha1.Middleware
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*traefikiov1alpha1.Middleware, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) *traefikiov1alpha1.Middleware); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefikiov1alpha1.Middleware)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMiddlewareManager_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type mockMiddlewareManager_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts v1.PatchOptions
//   - subresources ...string
func (_e *mockMiddlewareManager_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *mockMiddlewareManager_Patch_Call {
	return &mockMiddlewareManager_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *mockMiddlewareManager_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string)) *mockMiddlewareManager_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(v1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *mockMiddlewareManager_Patch_Call) Return(result *traefikiov1alpha1.Middleware, err error) *mockMiddlewareManager_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockMiddlewareManager_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*traefikiov1alpha1.Middleware, error)) *mockMiddlewareManager_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, middleware, opts
func (_m *mockMiddlewareManager) Update(ctx context.Context, middleware *traefikiov1alpha1.Middleware, opts v1.UpdateOptions) (*traefikiov1alpha1.Middleware, error) {
	ret := _m.Called(ctx, middleware, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *traefikiov1alpha1.Middleware
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *traefikiov1alpha1.Middleware, v1.UpdateOptions) (*traefikiov1alpha1.Middleware, error)); ok {
		return rf(ctx, middleware, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *traefikiov1alpha1.Middleware, v1.UpdateOptions) *traefikiov1alpha1.Middleware); ok {
		r0 = rf(ctx, middleware, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefikiov1alpha1.Middleware)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *traefikiov1alpha1.Middleware, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, middleware, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMiddlewareManager_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockMiddlewareManager_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - middleware *traefikiov1alpha1.Middleware
//   - opts v1.UpdateOptions
func (_e *mockMiddlewareManager_Expecter) Update(ctx interface{}, middleware interface{}, opts interface{}) *mockMiddlewareManager_Update_Call {
	return &mockMiddlewareManager_Update_Call{Call: _e.mock.On("Update", ctx, middleware, opts)}
}

func (_c *mockMiddlewareManager_Update_Call) Run(run func(ctx context.Context, middleware *traefikiov1alpha1.Middleware, opts v1.UpdateOptions)) *mockMiddlewareManager_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*traefikiov1alpha1.Middleware), args[2].(v1.UpdateOptions))
	})
	return _c
}

func (_c *mockMiddlewareManager_Update_Call) Return(_a0 *traefikiov1alpha1.Middleware, _a1 error) *mockMiddlewareManager_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMiddlewareManager_Update_Call) RunAndReturn(run func(context.Context, *traefikiov1alpha1.Middleware, v1.UpdateOptions) (*traefikiov1alpha1.Middleware, error)) *mockMiddlewareManager_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *mockMiddlewareManager) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMiddlewareManager_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type mockMiddlewareManager_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *mockMiddlewareManager_Expecter) Watch(ctx interface{}, opts interface{}) *mockMiddlewareManager_Watch_Call {
	return &mockMiddlewareManager_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *mockMiddlewareManager_Watch_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *mockMiddlewareManager_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *mockMiddlewareManager_Watch_Call) Return(_a0 watch.Interface, _a1 error) *mockMiddlewareManager_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMiddlewareManager_Watch_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (watch.Interface, error)) *mockMiddlewareManager_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// createOrUpdateReplacePathMiddleware provides a mock function with given fields: ctx, serviceName, cesService, ownerReferences
func (_m *mockMiddlewareManager) createOrUpdateReplacePathMiddleware(ctx context.Context, serviceName string, cesService CesService, ownerReferences []v1.OwnerReference) (string, error) {
	ret := _m.Called(ctx, serviceName, cesService, ownerReferences)

	if len(ret) == 0 {
		panic("no return value specified for createOrUpdateReplacePathMiddleware")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, CesService, []v1.OwnerReference) (string, error)); ok {
		return rf(ctx, serviceName, cesService, ownerReferences)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, CesService, []v1.OwnerReference) string); ok {
		r0 = rf(ctx, serviceName, cesService, ownerReferences)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, CesService, []v1.OwnerReference) error); ok {
		r1 = rf(ctx, serviceName, cesService, ownerReferences)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'createOrUpdateReplacePathMiddleware'
type mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call struct {
	*mock.Call
}

// createOrUpdateReplacePathMiddleware is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceName string
//   - cesService CesService
//   - ownerReferences []v1.OwnerReference
func (_e *mockMiddlewareManager_Expecter) createOrUpdateReplacePathMiddleware(ctx interface{}, serviceName interface{}, cesService interface{}, ownerReferences interface{}) *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call {
	return &mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call{Call: _e.mock.On("createOrUpdateReplacePathMiddleware", ctx, serviceName, cesService, ownerReferences)}
}

func (_c *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call) Run(run func(ctx context.Context, serviceName string, cesService CesService, ownerReferences []v1.OwnerReference)) *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(CesService), args[3].([]v1.OwnerReference))
	})
	return _c
}

func (_c *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call) Return(_a0 string, _a1 error) *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call) RunAndReturn(run func(context.Context, string, CesService, []v1.OwnerReference) (string, error)) *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call {
	_c.Call.Return(run)
	return _c
}

// newMockMiddlewareManager creates a new instance of mockMiddlewareManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMiddlewareManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMiddlewareManager {
	mock := &mockMiddlewareManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
