// Code generated by mockery v2.53.3. DO NOT EDIT.

package expose

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// mockMiddlewareManager is an autogenerated mock type for the middlewareManager type
type mockMiddlewareManager struct {
	mock.Mock
}

type mockMiddlewareManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMiddlewareManager) EXPECT() *mockMiddlewareManager_Expecter {
	return &mockMiddlewareManager_Expecter{mock: &_m.Mock}
}

// CreateOrUpdateAlternativeFQDNRedirectMiddleware provides a mock function with given fields: ctx, alternativeFQDNs, primaryFQDN, ownerReferences
func (_m *mockMiddlewareManager) CreateOrUpdateAlternativeFQDNRedirectMiddleware(ctx context.Context, alternativeFQDNs []string, primaryFQDN string, ownerReferences []v1.OwnerReference) (string, error) {
	ret := _m.Called(ctx, alternativeFQDNs, primaryFQDN, ownerReferences)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateAlternativeFQDNRedirectMiddleware")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string, []v1.OwnerReference) (string, error)); ok {
		return rf(ctx, alternativeFQDNs, primaryFQDN, ownerReferences)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string, []v1.OwnerReference) string); ok {
		r0 = rf(ctx, alternativeFQDNs, primaryFQDN, ownerReferences)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string, []v1.OwnerReference) error); ok {
		r1 = rf(ctx, alternativeFQDNs, primaryFQDN, ownerReferences)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateAlternativeFQDNRedirectMiddleware'
type mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call struct {
	*mock.Call
}

// CreateOrUpdateAlternativeFQDNRedirectMiddleware is a helper method to define mock.On call
//   - ctx context.Context
//   - alternativeFQDNs []string
//   - primaryFQDN string
//   - ownerReferences []v1.OwnerReference
func (_e *mockMiddlewareManager_Expecter) CreateOrUpdateAlternativeFQDNRedirectMiddleware(ctx interface{}, alternativeFQDNs interface{}, primaryFQDN interface{}, ownerReferences interface{}) *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call {
	return &mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call{Call: _e.mock.On("CreateOrUpdateAlternativeFQDNRedirectMiddleware", ctx, alternativeFQDNs, primaryFQDN, ownerReferences)}
}

func (_c *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call) Run(run func(ctx context.Context, alternativeFQDNs []string, primaryFQDN string, ownerReferences []v1.OwnerReference)) *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string), args[3].([]v1.OwnerReference))
	})
	return _c
}

func (_c *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call) Return(_a0 string, _a1 error) *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call) RunAndReturn(run func(context.Context, []string, string, []v1.OwnerReference) (string, error)) *mockMiddlewareManager_CreateOrUpdateAlternativeFQDNRedirectMiddleware_Call {
	_c.Call.Return(run)
	return _c
}

// createOrUpdateReplacePathMiddleware provides a mock function with given fields: ctx, serviceName, cesService, ownerReferences
func (_m *mockMiddlewareManager) createOrUpdateReplacePathMiddleware(ctx context.Context, serviceName string, cesService CesService, ownerReferences []v1.OwnerReference) (string, error) {
	ret := _m.Called(ctx, serviceName, cesService, ownerReferences)

	if len(ret) == 0 {
		panic("no return value specified for createOrUpdateReplacePathMiddleware")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, CesService, []v1.OwnerReference) (string, error)); ok {
		return rf(ctx, serviceName, cesService, ownerReferences)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, CesService, []v1.OwnerReference) string); ok {
		r0 = rf(ctx, serviceName, cesService, ownerReferences)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, CesService, []v1.OwnerReference) error); ok {
		r1 = rf(ctx, serviceName, cesService, ownerReferences)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'createOrUpdateReplacePathMiddleware'
type mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call struct {
	*mock.Call
}

// createOrUpdateReplacePathMiddleware is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceName string
//   - cesService CesService
//   - ownerReferences []v1.OwnerReference
func (_e *mockMiddlewareManager_Expecter) createOrUpdateReplacePathMiddleware(ctx interface{}, serviceName interface{}, cesService interface{}, ownerReferences interface{}) *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call {
	return &mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call{Call: _e.mock.On("createOrUpdateReplacePathMiddleware", ctx, serviceName, cesService, ownerReferences)}
}

func (_c *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call) Run(run func(ctx context.Context, serviceName string, cesService CesService, ownerReferences []v1.OwnerReference)) *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(CesService), args[3].([]v1.OwnerReference))
	})
	return _c
}

func (_c *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call) Return(_a0 string, _a1 error) *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call) RunAndReturn(run func(context.Context, string, CesService, []v1.OwnerReference) (string, error)) *mockMiddlewareManager_createOrUpdateReplacePathMiddleware_Call {
	_c.Call.Return(run)
	return _c
}

// newMockMiddlewareManager creates a new instance of mockMiddlewareManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMiddlewareManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMiddlewareManager {
	mock := &mockMiddlewareManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
