// Code generated by mockery v2.53.5. DO NOT EDIT.

package expose

import (
	domain "github.com/cloudogu/k8s-service-discovery/v2/controllers/expose/domain"
	mock "github.com/stretchr/testify/mock"
	v1alpha1 "github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/traefikio/v1alpha1"
	v1 "k8s.io/api/networking/v1"
)

// mockIngressGenerator is an autogenerated mock type for the ingressGenerator type
type mockIngressGenerator struct {
	mock.Mock
}

type mockIngressGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIngressGenerator) EXPECT() *mockIngressGenerator_Expecter {
	return &mockIngressGenerator_Expecter{mock: &_m.Mock}
}

// GenerateWithMiddlewares provides a mock function with given fields: definition
func (_m *mockIngressGenerator) GenerateWithMiddlewares(definition domain.IngressDefinition) ([]*v1.Ingress, []*v1alpha1.Middleware) {
	ret := _m.Called(definition)

	if len(ret) == 0 {
		panic("no return value specified for GenerateWithMiddlewares")
	}

	var r0 []*v1.Ingress
	var r1 []*v1alpha1.Middleware
	if rf, ok := ret.Get(0).(func(domain.IngressDefinition) ([]*v1.Ingress, []*v1alpha1.Middleware)); ok {
		return rf(definition)
	}
	if rf, ok := ret.Get(0).(func(domain.IngressDefinition) []*v1.Ingress); ok {
		r0 = rf(definition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.Ingress)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.IngressDefinition) []*v1alpha1.Middleware); ok {
		r1 = rf(definition)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*v1alpha1.Middleware)
		}
	}

	return r0, r1
}

// mockIngressGenerator_GenerateWithMiddlewares_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateWithMiddlewares'
type mockIngressGenerator_GenerateWithMiddlewares_Call struct {
	*mock.Call
}

// GenerateWithMiddlewares is a helper method to define mock.On call
//   - definition domain.IngressDefinition
func (_e *mockIngressGenerator_Expecter) GenerateWithMiddlewares(definition interface{}) *mockIngressGenerator_GenerateWithMiddlewares_Call {
	return &mockIngressGenerator_GenerateWithMiddlewares_Call{Call: _e.mock.On("GenerateWithMiddlewares", definition)}
}

func (_c *mockIngressGenerator_GenerateWithMiddlewares_Call) Run(run func(definition domain.IngressDefinition)) *mockIngressGenerator_GenerateWithMiddlewares_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.IngressDefinition))
	})
	return _c
}

func (_c *mockIngressGenerator_GenerateWithMiddlewares_Call) Return(_a0 []*v1.Ingress, _a1 []*v1alpha1.Middleware) *mockIngressGenerator_GenerateWithMiddlewares_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressGenerator_GenerateWithMiddlewares_Call) RunAndReturn(run func(domain.IngressDefinition) ([]*v1.Ingress, []*v1alpha1.Middleware)) *mockIngressGenerator_GenerateWithMiddlewares_Call {
	_c.Call.Return(run)
	return _c
}

// newMockIngressGenerator creates a new instance of mockIngressGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIngressGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIngressGenerator {
	mock := &mockIngressGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
