// Code generated by mockery v2.52.4. DO NOT EDIT.

package expose

import (
	context "context"

	types "github.com/cloudogu/k8s-service-discovery/v2/internal/types"
	mock "github.com/stretchr/testify/mock"

	util "github.com/cloudogu/k8s-service-discovery/v2/controllers/util"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// mockIngressController is an autogenerated mock type for the ingressController type
type mockIngressController struct {
	mock.Mock
}

type mockIngressController_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIngressController) EXPECT() *mockIngressController_Expecter {
	return &mockIngressController_Expecter{mock: &_m.Mock}
}

// DeleteExposedPorts provides a mock function with given fields: ctx, namespace, targetServiceName
func (_m *mockIngressController) DeleteExposedPorts(ctx context.Context, namespace string, targetServiceName string) error {
	ret := _m.Called(ctx, namespace, targetServiceName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExposedPorts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespace, targetServiceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockIngressController_DeleteExposedPorts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExposedPorts'
type mockIngressController_DeleteExposedPorts_Call struct {
	*mock.Call
}

// DeleteExposedPorts is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - targetServiceName string
func (_e *mockIngressController_Expecter) DeleteExposedPorts(ctx interface{}, namespace interface{}, targetServiceName interface{}) *mockIngressController_DeleteExposedPorts_Call {
	return &mockIngressController_DeleteExposedPorts_Call{Call: _e.mock.On("DeleteExposedPorts", ctx, namespace, targetServiceName)}
}

func (_c *mockIngressController_DeleteExposedPorts_Call) Run(run func(ctx context.Context, namespace string, targetServiceName string)) *mockIngressController_DeleteExposedPorts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockIngressController_DeleteExposedPorts_Call) Return(_a0 error) *mockIngressController_DeleteExposedPorts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIngressController_DeleteExposedPorts_Call) RunAndReturn(run func(context.Context, string, string) error) *mockIngressController_DeleteExposedPorts_Call {
	_c.Call.Return(run)
	return _c
}

// ExposeOrUpdateExposedPorts provides a mock function with given fields: ctx, namespace, targetServiceName, exposedPorts
func (_m *mockIngressController) ExposeOrUpdateExposedPorts(ctx context.Context, namespace string, targetServiceName string, exposedPorts util.ExposedPorts) error {
	ret := _m.Called(ctx, namespace, targetServiceName, exposedPorts)

	if len(ret) == 0 {
		panic("no return value specified for ExposeOrUpdateExposedPorts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, util.ExposedPorts) error); ok {
		r0 = rf(ctx, namespace, targetServiceName, exposedPorts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockIngressController_ExposeOrUpdateExposedPorts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExposeOrUpdateExposedPorts'
type mockIngressController_ExposeOrUpdateExposedPorts_Call struct {
	*mock.Call
}

// ExposeOrUpdateExposedPorts is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - targetServiceName string
//   - exposedPorts util.ExposedPorts
func (_e *mockIngressController_Expecter) ExposeOrUpdateExposedPorts(ctx interface{}, namespace interface{}, targetServiceName interface{}, exposedPorts interface{}) *mockIngressController_ExposeOrUpdateExposedPorts_Call {
	return &mockIngressController_ExposeOrUpdateExposedPorts_Call{Call: _e.mock.On("ExposeOrUpdateExposedPorts", ctx, namespace, targetServiceName, exposedPorts)}
}

func (_c *mockIngressController_ExposeOrUpdateExposedPorts_Call) Run(run func(ctx context.Context, namespace string, targetServiceName string, exposedPorts util.ExposedPorts)) *mockIngressController_ExposeOrUpdateExposedPorts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(util.ExposedPorts))
	})
	return _c
}

func (_c *mockIngressController_ExposeOrUpdateExposedPorts_Call) Return(_a0 error) *mockIngressController_ExposeOrUpdateExposedPorts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIngressController_ExposeOrUpdateExposedPorts_Call) RunAndReturn(run func(context.Context, string, string, util.ExposedPorts) error) *mockIngressController_ExposeOrUpdateExposedPorts_Call {
	_c.Call.Return(run)
	return _c
}

// ExposePorts provides a mock function with given fields: ctx, namespace, exposedPorts, owner
func (_m *mockIngressController) ExposePorts(ctx context.Context, namespace string, exposedPorts types.ExposedPorts, owner *v1.OwnerReference) {
	_m.Called(ctx, namespace, exposedPorts, owner)
}

// mockIngressController_ExposePorts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExposePorts'
type mockIngressController_ExposePorts_Call struct {
	*mock.Call
}

// ExposePorts is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - exposedPorts types.ExposedPorts
//   - owner *v1.OwnerReference
func (_e *mockIngressController_Expecter) ExposePorts(ctx interface{}, namespace interface{}, exposedPorts interface{}, owner interface{}) *mockIngressController_ExposePorts_Call {
	return &mockIngressController_ExposePorts_Call{Call: _e.mock.On("ExposePorts", ctx, namespace, exposedPorts, owner)}
}

func (_c *mockIngressController_ExposePorts_Call) Run(run func(ctx context.Context, namespace string, exposedPorts types.ExposedPorts, owner *v1.OwnerReference)) *mockIngressController_ExposePorts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(types.ExposedPorts), args[3].(*v1.OwnerReference))
	})
	return _c
}

func (_c *mockIngressController_ExposePorts_Call) Return() *mockIngressController_ExposePorts_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockIngressController_ExposePorts_Call) RunAndReturn(run func(context.Context, string, types.ExposedPorts, *v1.OwnerReference)) *mockIngressController_ExposePorts_Call {
	_c.Run(run)
	return _c
}

// GetControllerSpec provides a mock function with no fields
func (_m *mockIngressController) GetControllerSpec() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetControllerSpec")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// mockIngressController_GetControllerSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetControllerSpec'
type mockIngressController_GetControllerSpec_Call struct {
	*mock.Call
}

// GetControllerSpec is a helper method to define mock.On call
func (_e *mockIngressController_Expecter) GetControllerSpec() *mockIngressController_GetControllerSpec_Call {
	return &mockIngressController_GetControllerSpec_Call{Call: _e.mock.On("GetControllerSpec")}
}

func (_c *mockIngressController_GetControllerSpec_Call) Run(run func()) *mockIngressController_GetControllerSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockIngressController_GetControllerSpec_Call) Return(_a0 string) *mockIngressController_GetControllerSpec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIngressController_GetControllerSpec_Call) RunAndReturn(run func() string) *mockIngressController_GetControllerSpec_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *mockIngressController) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// mockIngressController_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type mockIngressController_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *mockIngressController_Expecter) GetName() *mockIngressController_GetName_Call {
	return &mockIngressController_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *mockIngressController_GetName_Call) Run(run func()) *mockIngressController_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockIngressController_GetName_Call) Return(_a0 string) *mockIngressController_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIngressController_GetName_Call) RunAndReturn(run func() string) *mockIngressController_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetRewriteAnnotationKey provides a mock function with no fields
func (_m *mockIngressController) GetRewriteAnnotationKey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRewriteAnnotationKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// mockIngressController_GetRewriteAnnotationKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRewriteAnnotationKey'
type mockIngressController_GetRewriteAnnotationKey_Call struct {
	*mock.Call
}

// GetRewriteAnnotationKey is a helper method to define mock.On call
func (_e *mockIngressController_Expecter) GetRewriteAnnotationKey() *mockIngressController_GetRewriteAnnotationKey_Call {
	return &mockIngressController_GetRewriteAnnotationKey_Call{Call: _e.mock.On("GetRewriteAnnotationKey")}
}

func (_c *mockIngressController_GetRewriteAnnotationKey_Call) Run(run func()) *mockIngressController_GetRewriteAnnotationKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockIngressController_GetRewriteAnnotationKey_Call) Return(_a0 string) *mockIngressController_GetRewriteAnnotationKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIngressController_GetRewriteAnnotationKey_Call) RunAndReturn(run func() string) *mockIngressController_GetRewriteAnnotationKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetSelector provides a mock function with no fields
func (_m *mockIngressController) GetSelector() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSelector")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// mockIngressController_GetSelector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSelector'
type mockIngressController_GetSelector_Call struct {
	*mock.Call
}

// GetSelector is a helper method to define mock.On call
func (_e *mockIngressController_Expecter) GetSelector() *mockIngressController_GetSelector_Call {
	return &mockIngressController_GetSelector_Call{Call: _e.mock.On("GetSelector")}
}

func (_c *mockIngressController_GetSelector_Call) Run(run func()) *mockIngressController_GetSelector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockIngressController_GetSelector_Call) Return(_a0 map[string]string) *mockIngressController_GetSelector_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIngressController_GetSelector_Call) RunAndReturn(run func() map[string]string) *mockIngressController_GetSelector_Call {
	_c.Call.Return(run)
	return _c
}

// GetUseRegexKey provides a mock function with no fields
func (_m *mockIngressController) GetUseRegexKey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUseRegexKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// mockIngressController_GetUseRegexKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUseRegexKey'
type mockIngressController_GetUseRegexKey_Call struct {
	*mock.Call
}

// GetUseRegexKey is a helper method to define mock.On call
func (_e *mockIngressController_Expecter) GetUseRegexKey() *mockIngressController_GetUseRegexKey_Call {
	return &mockIngressController_GetUseRegexKey_Call{Call: _e.mock.On("GetUseRegexKey")}
}

func (_c *mockIngressController_GetUseRegexKey_Call) Run(run func()) *mockIngressController_GetUseRegexKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockIngressController_GetUseRegexKey_Call) Return(_a0 string) *mockIngressController_GetUseRegexKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIngressController_GetUseRegexKey_Call) RunAndReturn(run func() string) *mockIngressController_GetUseRegexKey_Call {
	_c.Call.Return(run)
	return _c
}

// newMockIngressController creates a new instance of mockIngressController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIngressController(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIngressController {
	mock := &mockIngressController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
