// Code generated by mockery v2.53.5. DO NOT EDIT.

package expose

import (
	context "context"

	v1 "github.com/cloudogu/k8s-exposition-lib/api/v1"
	domain "github.com/cloudogu/k8s-service-discovery/v2/controllers/expose/domain"
	mock "github.com/stretchr/testify/mock"
	corev1 "k8s.io/api/core/v1"
)

// mockIngressDefinitionCreator is an autogenerated mock type for the ingressDefinitionCreator type
type mockIngressDefinitionCreator struct {
	mock.Mock
}

type mockIngressDefinitionCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIngressDefinitionCreator) EXPECT() *mockIngressDefinitionCreator_Expecter {
	return &mockIngressDefinitionCreator_Expecter{mock: &_m.Mock}
}

// CreateFromExposition provides a mock function with given fields: ctx, exposition
func (_m *mockIngressDefinitionCreator) CreateFromExposition(ctx context.Context, exposition *v1.Exposition) (domain.IngressDefinition, error) {
	ret := _m.Called(ctx, exposition)

	if len(ret) == 0 {
		panic("no return value specified for CreateFromExposition")
	}

	var r0 domain.IngressDefinition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Exposition) (domain.IngressDefinition, error)); ok {
		return rf(ctx, exposition)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Exposition) domain.IngressDefinition); ok {
		r0 = rf(ctx, exposition)
	} else {
		r0 = ret.Get(0).(domain.IngressDefinition)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Exposition) error); ok {
		r1 = rf(ctx, exposition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressDefinitionCreator_CreateFromExposition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFromExposition'
type mockIngressDefinitionCreator_CreateFromExposition_Call struct {
	*mock.Call
}

// CreateFromExposition is a helper method to define mock.On call
//   - ctx context.Context
//   - exposition *v1.Exposition
func (_e *mockIngressDefinitionCreator_Expecter) CreateFromExposition(ctx interface{}, exposition interface{}) *mockIngressDefinitionCreator_CreateFromExposition_Call {
	return &mockIngressDefinitionCreator_CreateFromExposition_Call{Call: _e.mock.On("CreateFromExposition", ctx, exposition)}
}

func (_c *mockIngressDefinitionCreator_CreateFromExposition_Call) Run(run func(ctx context.Context, exposition *v1.Exposition)) *mockIngressDefinitionCreator_CreateFromExposition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Exposition))
	})
	return _c
}

func (_c *mockIngressDefinitionCreator_CreateFromExposition_Call) Return(_a0 domain.IngressDefinition, _a1 error) *mockIngressDefinitionCreator_CreateFromExposition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressDefinitionCreator_CreateFromExposition_Call) RunAndReturn(run func(context.Context, *v1.Exposition) (domain.IngressDefinition, error)) *mockIngressDefinitionCreator_CreateFromExposition_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFromService provides a mock function with given fields: ctx, service
func (_m *mockIngressDefinitionCreator) CreateFromService(ctx context.Context, service *corev1.Service) (domain.IngressDefinition, error) {
	ret := _m.Called(ctx, service)

	if len(ret) == 0 {
		panic("no return value specified for CreateFromService")
	}

	var r0 domain.IngressDefinition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.Service) (domain.IngressDefinition, error)); ok {
		return rf(ctx, service)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.Service) domain.IngressDefinition); ok {
		r0 = rf(ctx, service)
	} else {
		r0 = ret.Get(0).(domain.IngressDefinition)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1.Service) error); ok {
		r1 = rf(ctx, service)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressDefinitionCreator_CreateFromService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFromService'
type mockIngressDefinitionCreator_CreateFromService_Call struct {
	*mock.Call
}

// CreateFromService is a helper method to define mock.On call
//   - ctx context.Context
//   - service *corev1.Service
func (_e *mockIngressDefinitionCreator_Expecter) CreateFromService(ctx interface{}, service interface{}) *mockIngressDefinitionCreator_CreateFromService_Call {
	return &mockIngressDefinitionCreator_CreateFromService_Call{Call: _e.mock.On("CreateFromService", ctx, service)}
}

func (_c *mockIngressDefinitionCreator_CreateFromService_Call) Run(run func(ctx context.Context, service *corev1.Service)) *mockIngressDefinitionCreator_CreateFromService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1.Service))
	})
	return _c
}

func (_c *mockIngressDefinitionCreator_CreateFromService_Call) Return(_a0 domain.IngressDefinition, _a1 error) *mockIngressDefinitionCreator_CreateFromService_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressDefinitionCreator_CreateFromService_Call) RunAndReturn(run func(context.Context, *corev1.Service) (domain.IngressDefinition, error)) *mockIngressDefinitionCreator_CreateFromService_Call {
	_c.Call.Return(run)
	return _c
}

// newMockIngressDefinitionCreator creates a new instance of mockIngressDefinitionCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIngressDefinitionCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIngressDefinitionCreator {
	mock := &mockIngressDefinitionCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
