// Code generated by mockery v2.53.5. DO NOT EDIT.

package expose

import (
	domain "github.com/cloudogu/k8s-service-discovery/v2/controllers/expose/domain"
	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/networking/v1"
)

// mockNetworkPolicyGenerator is an autogenerated mock type for the networkPolicyGenerator type
type mockNetworkPolicyGenerator struct {
	mock.Mock
}

type mockNetworkPolicyGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockNetworkPolicyGenerator) EXPECT() *mockNetworkPolicyGenerator_Expecter {
	return &mockNetworkPolicyGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: definition
func (_m *mockNetworkPolicyGenerator) Generate(definition domain.ExposedPortsDefinition) []*v1.NetworkPolicy {
	ret := _m.Called(definition)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 []*v1.NetworkPolicy
	if rf, ok := ret.Get(0).(func(domain.ExposedPortsDefinition) []*v1.NetworkPolicy); ok {
		r0 = rf(definition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.NetworkPolicy)
		}
	}

	return r0
}

// mockNetworkPolicyGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type mockNetworkPolicyGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - definition domain.ExposedPortsDefinition
func (_e *mockNetworkPolicyGenerator_Expecter) Generate(definition interface{}) *mockNetworkPolicyGenerator_Generate_Call {
	return &mockNetworkPolicyGenerator_Generate_Call{Call: _e.mock.On("Generate", definition)}
}

func (_c *mockNetworkPolicyGenerator_Generate_Call) Run(run func(definition domain.ExposedPortsDefinition)) *mockNetworkPolicyGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.ExposedPortsDefinition))
	})
	return _c
}

func (_c *mockNetworkPolicyGenerator_Generate_Call) Return(_a0 []*v1.NetworkPolicy) *mockNetworkPolicyGenerator_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockNetworkPolicyGenerator_Generate_Call) RunAndReturn(run func(domain.ExposedPortsDefinition) []*v1.NetworkPolicy) *mockNetworkPolicyGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockNetworkPolicyGenerator creates a new instance of mockNetworkPolicyGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockNetworkPolicyGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockNetworkPolicyGenerator {
	mock := &mockNetworkPolicyGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
