// Code generated by mockery v2.52.4. DO NOT EDIT.

package warp

import (
	context "context"

	dogu "github.com/cloudogu/ces-commons-lib/dogu"
	mock "github.com/stretchr/testify/mock"
)

// MockDoguVersionRegistry is an autogenerated mock type for the DoguVersionRegistry type
type MockDoguVersionRegistry struct {
	mock.Mock
}

type MockDoguVersionRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguVersionRegistry) EXPECT() *MockDoguVersionRegistry_Expecter {
	return &MockDoguVersionRegistry_Expecter{mock: &_m.Mock}
}

// GetCurrentOfAll provides a mock function with given fields: _a0
func (_m *MockDoguVersionRegistry) GetCurrentOfAll(_a0 context.Context) ([]dogu.SimpleNameVersion, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentOfAll")
	}

	var r0 []dogu.SimpleNameVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dogu.SimpleNameVersion, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dogu.SimpleNameVersion); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dogu.SimpleNameVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguVersionRegistry_GetCurrentOfAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentOfAll'
type MockDoguVersionRegistry_GetCurrentOfAll_Call struct {
	*mock.Call
}

// GetCurrentOfAll is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockDoguVersionRegistry_Expecter) GetCurrentOfAll(_a0 interface{}) *MockDoguVersionRegistry_GetCurrentOfAll_Call {
	return &MockDoguVersionRegistry_GetCurrentOfAll_Call{Call: _e.mock.On("GetCurrentOfAll", _a0)}
}

func (_c *MockDoguVersionRegistry_GetCurrentOfAll_Call) Run(run func(_a0 context.Context)) *MockDoguVersionRegistry_GetCurrentOfAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDoguVersionRegistry_GetCurrentOfAll_Call) Return(_a0 []dogu.SimpleNameVersion, _a1 error) *MockDoguVersionRegistry_GetCurrentOfAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguVersionRegistry_GetCurrentOfAll_Call) RunAndReturn(run func(context.Context) ([]dogu.SimpleNameVersion, error)) *MockDoguVersionRegistry_GetCurrentOfAll_Call {
	_c.Call.Return(run)
	return _c
}

// WatchAllCurrent provides a mock function with given fields: _a0
func (_m *MockDoguVersionRegistry) WatchAllCurrent(_a0 context.Context) (<-chan dogu.CurrentVersionsWatchResult, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for WatchAllCurrent")
	}

	var r0 <-chan dogu.CurrentVersionsWatchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan dogu.CurrentVersionsWatchResult, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan dogu.CurrentVersionsWatchResult); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan dogu.CurrentVersionsWatchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguVersionRegistry_WatchAllCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchAllCurrent'
type MockDoguVersionRegistry_WatchAllCurrent_Call struct {
	*mock.Call
}

// WatchAllCurrent is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockDoguVersionRegistry_Expecter) WatchAllCurrent(_a0 interface{}) *MockDoguVersionRegistry_WatchAllCurrent_Call {
	return &MockDoguVersionRegistry_WatchAllCurrent_Call{Call: _e.mock.On("WatchAllCurrent", _a0)}
}

func (_c *MockDoguVersionRegistry_WatchAllCurrent_Call) Run(run func(_a0 context.Context)) *MockDoguVersionRegistry_WatchAllCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDoguVersionRegistry_WatchAllCurrent_Call) Return(_a0 <-chan dogu.CurrentVersionsWatchResult, _a1 error) *MockDoguVersionRegistry_WatchAllCurrent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguVersionRegistry_WatchAllCurrent_Call) RunAndReturn(run func(context.Context) (<-chan dogu.CurrentVersionsWatchResult, error)) *MockDoguVersionRegistry_WatchAllCurrent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguVersionRegistry creates a new instance of MockDoguVersionRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguVersionRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguVersionRegistry {
	mock := &MockDoguVersionRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
