// Code generated by mockery v2.20.0. DO NOT EDIT.

package warp

import (
	logr "github.com/go-logr/logr"
	mock "github.com/stretchr/testify/mock"
)

// MockLogSink is an autogenerated mock type for the LogSink type
type MockLogSink struct {
	mock.Mock
}

type MockLogSink_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogSink) EXPECT() *MockLogSink_Expecter {
	return &MockLogSink_Expecter{mock: &_m.Mock}
}

// Enabled provides a mock function with given fields: level
func (_m *MockLogSink) Enabled(level int) bool {
	ret := _m.Called(level)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(level)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockLogSink_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MockLogSink_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
//   - level int
func (_e *MockLogSink_Expecter) Enabled(level interface{}) *MockLogSink_Enabled_Call {
	return &MockLogSink_Enabled_Call{Call: _e.mock.On("Enabled", level)}
}

func (_c *MockLogSink_Enabled_Call) Run(run func(level int)) *MockLogSink_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockLogSink_Enabled_Call) Return(_a0 bool) *MockLogSink_Enabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogSink_Enabled_Call) RunAndReturn(run func(int) bool) *MockLogSink_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with given fields: err, msg, keysAndValues
func (_m *MockLogSink) Error(err error, msg string, keysAndValues ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, err, msg)
	_ca = append(_ca, keysAndValues...)
	_m.Called(_ca...)
}

// MockLogSink_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogSink_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - err error
//   - msg string
//   - keysAndValues ...interface{}
func (_e *MockLogSink_Expecter) Error(err interface{}, msg interface{}, keysAndValues ...interface{}) *MockLogSink_Error_Call {
	return &MockLogSink_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{err, msg}, keysAndValues...)...)}
}

func (_c *MockLogSink_Error_Call) Run(run func(err error, msg string, keysAndValues ...interface{})) *MockLogSink_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(error), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogSink_Error_Call) Return() *MockLogSink_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogSink_Error_Call) RunAndReturn(run func(error, string, ...interface{})) *MockLogSink_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: level, msg, keysAndValues
func (_m *MockLogSink) Info(level int, msg string, keysAndValues ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, level, msg)
	_ca = append(_ca, keysAndValues...)
	_m.Called(_ca...)
}

// MockLogSink_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogSink_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - level int
//   - msg string
//   - keysAndValues ...interface{}
func (_e *MockLogSink_Expecter) Info(level interface{}, msg interface{}, keysAndValues ...interface{}) *MockLogSink_Info_Call {
	return &MockLogSink_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{level, msg}, keysAndValues...)...)}
}

func (_c *MockLogSink_Info_Call) Run(run func(level int, msg string, keysAndValues ...interface{})) *MockLogSink_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(int), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogSink_Info_Call) Return() *MockLogSink_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogSink_Info_Call) RunAndReturn(run func(int, string, ...interface{})) *MockLogSink_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function with given fields: info
func (_m *MockLogSink) Init(info logr.RuntimeInfo) {
	_m.Called(info)
}

// MockLogSink_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockLogSink_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - info logr.RuntimeInfo
func (_e *MockLogSink_Expecter) Init(info interface{}) *MockLogSink_Init_Call {
	return &MockLogSink_Init_Call{Call: _e.mock.On("Init", info)}
}

func (_c *MockLogSink_Init_Call) Run(run func(info logr.RuntimeInfo)) *MockLogSink_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(logr.RuntimeInfo))
	})
	return _c
}

func (_c *MockLogSink_Init_Call) Return() *MockLogSink_Init_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogSink_Init_Call) RunAndReturn(run func(logr.RuntimeInfo)) *MockLogSink_Init_Call {
	_c.Call.Return(run)
	return _c
}

// WithName provides a mock function with given fields: name
func (_m *MockLogSink) WithName(name string) logr.LogSink {
	ret := _m.Called(name)

	var r0 logr.LogSink
	if rf, ok := ret.Get(0).(func(string) logr.LogSink); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logr.LogSink)
		}
	}

	return r0
}

// MockLogSink_WithName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithName'
type MockLogSink_WithName_Call struct {
	*mock.Call
}

// WithName is a helper method to define mock.On call
//   - name string
func (_e *MockLogSink_Expecter) WithName(name interface{}) *MockLogSink_WithName_Call {
	return &MockLogSink_WithName_Call{Call: _e.mock.On("WithName", name)}
}

func (_c *MockLogSink_WithName_Call) Run(run func(name string)) *MockLogSink_WithName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLogSink_WithName_Call) Return(_a0 logr.LogSink) *MockLogSink_WithName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogSink_WithName_Call) RunAndReturn(run func(string) logr.LogSink) *MockLogSink_WithName_Call {
	_c.Call.Return(run)
	return _c
}

// WithValues provides a mock function with given fields: keysAndValues
func (_m *MockLogSink) WithValues(keysAndValues ...interface{}) logr.LogSink {
	var _ca []interface{}
	_ca = append(_ca, keysAndValues...)
	ret := _m.Called(_ca...)

	var r0 logr.LogSink
	if rf, ok := ret.Get(0).(func(...interface{}) logr.LogSink); ok {
		r0 = rf(keysAndValues...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logr.LogSink)
		}
	}

	return r0
}

// MockLogSink_WithValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithValues'
type MockLogSink_WithValues_Call struct {
	*mock.Call
}

// WithValues is a helper method to define mock.On call
//   - keysAndValues ...interface{}
func (_e *MockLogSink_Expecter) WithValues(keysAndValues ...interface{}) *MockLogSink_WithValues_Call {
	return &MockLogSink_WithValues_Call{Call: _e.mock.On("WithValues",
		append([]interface{}{}, keysAndValues...)...)}
}

func (_c *MockLogSink_WithValues_Call) Run(run func(keysAndValues ...interface{})) *MockLogSink_WithValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogSink_WithValues_Call) Return(_a0 logr.LogSink) *MockLogSink_WithValues_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogSink_WithValues_Call) RunAndReturn(run func(...interface{}) logr.LogSink) *MockLogSink_WithValues_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockLogSink interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockLogSink creates a new instance of MockLogSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockLogSink(t mockConstructorTestingTNewMockLogSink) *MockLogSink {
	mock := &MockLogSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
