apiVersion: v1
kind: Service
metadata:
  name: scm-2222
  labels:
    service-discorvery.cloudogu.com/type: exposed_service
spec:
  type: NodePort
  selector:
    app: scm
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
      nodePort: 32222