apiVersion: v1
kind: Service
metadata:
  name: nexus-8082
  labels:
    service-discorvery.cloudogu.com/type: webapp
spec:
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082