apiVersion: v1
kind: Service
metadata:
  name: nexus-8082
  labels:
    service-discorvery.cloudogu.com/type: webapp
    service-discorvery.cloudogu.com/additional_pass: '[{"name": "docker-registry", "location": "v2", "pass": "nexus/repository/docker-registry/v2/"}]'
spec:
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082