apiVersion: v1
kind: Service
metadata:
  name: nexus
  annotations:
    service-discovery.cloudogu.com/ces-services: '[{"name":"nexus-min", "port":8082, "location":"/nexus", "pass": "/nexus"}]'
spec:
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082