// Code generated by mockery v2.53.5. DO NOT EDIT.

package controllers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMaintenanceAdapter is an autogenerated mock type for the MaintenanceAdapter type
type MockMaintenanceAdapter struct {
	mock.Mock
}

type MockMaintenanceAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMaintenanceAdapter) EXPECT() *MockMaintenanceAdapter_Expecter {
	return &MockMaintenanceAdapter_Expecter{mock: &_m.Mock}
}

// IsActive provides a mock function with given fields: ctx
func (_m *MockMaintenanceAdapter) IsActive(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsActive")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMaintenanceAdapter_IsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsActive'
type MockMaintenanceAdapter_IsActive_Call struct {
	*mock.Call
}

// IsActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMaintenanceAdapter_Expecter) IsActive(ctx interface{}) *MockMaintenanceAdapter_IsActive_Call {
	return &MockMaintenanceAdapter_IsActive_Call{Call: _e.mock.On("IsActive", ctx)}
}

func (_c *MockMaintenanceAdapter_IsActive_Call) Run(run func(ctx context.Context)) *MockMaintenanceAdapter_IsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMaintenanceAdapter_IsActive_Call) Return(_a0 bool, _a1 error) *MockMaintenanceAdapter_IsActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMaintenanceAdapter_IsActive_Call) RunAndReturn(run func(context.Context) (bool, error)) *MockMaintenanceAdapter_IsActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMaintenanceAdapter creates a new instance of MockMaintenanceAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMaintenanceAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMaintenanceAdapter {
	mock := &MockMaintenanceAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
