// Code generated by mockery v2.53.3. DO NOT EDIT.

package controllers

import (
	context "context"

	repository "github.com/cloudogu/k8s-registry-lib/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockMaintenanceAdapter is an autogenerated mock type for the MaintenanceAdapter type
type MockMaintenanceAdapter struct {
	mock.Mock
}

type MockMaintenanceAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMaintenanceAdapter) EXPECT() *MockMaintenanceAdapter_Expecter {
	return &MockMaintenanceAdapter_Expecter{mock: &_m.Mock}
}

// GetStatus provides a mock function with given fields: ctx
func (_m *MockMaintenanceAdapter) GetStatus(ctx context.Context) (repository.MaintenanceModeDescription, bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 repository.MaintenanceModeDescription
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.MaintenanceModeDescription, bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.MaintenanceModeDescription); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(repository.MaintenanceModeDescription)
	}

	if rf, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMaintenanceAdapter_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockMaintenanceAdapter_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMaintenanceAdapter_Expecter) GetStatus(ctx interface{}) *MockMaintenanceAdapter_GetStatus_Call {
	return &MockMaintenanceAdapter_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx)}
}

func (_c *MockMaintenanceAdapter_GetStatus_Call) Run(run func(ctx context.Context)) *MockMaintenanceAdapter_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMaintenanceAdapter_GetStatus_Call) Return(_a0 repository.MaintenanceModeDescription, _a1 bool, _a2 error) *MockMaintenanceAdapter_GetStatus_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMaintenanceAdapter_GetStatus_Call) RunAndReturn(run func(context.Context) (repository.MaintenanceModeDescription, bool, error)) *MockMaintenanceAdapter_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMaintenanceAdapter creates a new instance of MockMaintenanceAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMaintenanceAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMaintenanceAdapter {
	mock := &MockMaintenanceAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
