// Code generated by mockery v2.52.4. DO NOT EDIT.

package controllers

import mock "github.com/stretchr/testify/mock"

// MockIngressControllerSelector is an autogenerated mock type for the IngressControllerSelector type
type MockIngressControllerSelector struct {
	mock.Mock
}

type MockIngressControllerSelector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngressControllerSelector) EXPECT() *MockIngressControllerSelector_Expecter {
	return &MockIngressControllerSelector_Expecter{mock: &_m.Mock}
}

// GetSelector provides a mock function with no fields
func (_m *MockIngressControllerSelector) GetSelector() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSelector")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// MockIngressControllerSelector_GetSelector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSelector'
type MockIngressControllerSelector_GetSelector_Call struct {
	*mock.Call
}

// GetSelector is a helper method to define mock.On call
func (_e *MockIngressControllerSelector_Expecter) GetSelector() *MockIngressControllerSelector_GetSelector_Call {
	return &MockIngressControllerSelector_GetSelector_Call{Call: _e.mock.On("GetSelector")}
}

func (_c *MockIngressControllerSelector_GetSelector_Call) Run(run func()) *MockIngressControllerSelector_GetSelector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIngressControllerSelector_GetSelector_Call) Return(_a0 map[string]string) *MockIngressControllerSelector_GetSelector_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIngressControllerSelector_GetSelector_Call) RunAndReturn(run func() map[string]string) *MockIngressControllerSelector_GetSelector_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIngressControllerSelector creates a new instance of MockIngressControllerSelector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngressControllerSelector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngressControllerSelector {
	mock := &MockIngressControllerSelector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
