// Code generated by mockery v2.53.3. DO NOT EDIT.

package controllers

import (
	context "context"

	types "github.com/cloudogu/k8s-service-discovery/v2/internal/types"
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MockPortExposer is an autogenerated mock type for the PortExposer type
type MockPortExposer struct {
	mock.Mock
}

type MockPortExposer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPortExposer) EXPECT() *MockPortExposer_Expecter {
	return &MockPortExposer_Expecter{mock: &_m.Mock}
}

// ExposePorts provides a mock function with given fields: ctx, namespace, exposedPorts, owner
func (_m *MockPortExposer) ExposePorts(ctx context.Context, namespace string, exposedPorts types.ExposedPorts, owner *v1.OwnerReference) error {
	ret := _m.Called(ctx, namespace, exposedPorts, owner)

	if len(ret) == 0 {
		panic("no return value specified for ExposePorts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.ExposedPorts, *v1.OwnerReference) error); ok {
		r0 = rf(ctx, namespace, exposedPorts, owner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPortExposer_ExposePorts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExposePorts'
type MockPortExposer_ExposePorts_Call struct {
	*mock.Call
}

// ExposePorts is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - exposedPorts types.ExposedPorts
//   - owner *v1.OwnerReference
func (_e *MockPortExposer_Expecter) ExposePorts(ctx interface{}, namespace interface{}, exposedPorts interface{}, owner interface{}) *MockPortExposer_ExposePorts_Call {
	return &MockPortExposer_ExposePorts_Call{Call: _e.mock.On("ExposePorts", ctx, namespace, exposedPorts, owner)}
}

func (_c *MockPortExposer_ExposePorts_Call) Run(run func(ctx context.Context, namespace string, exposedPorts types.ExposedPorts, owner *v1.OwnerReference)) *MockPortExposer_ExposePorts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(types.ExposedPorts), args[3].(*v1.OwnerReference))
	})
	return _c
}

func (_c *MockPortExposer_ExposePorts_Call) Return(_a0 error) *MockPortExposer_ExposePorts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPortExposer_ExposePorts_Call) RunAndReturn(run func(context.Context, string, types.ExposedPorts, *v1.OwnerReference) error) *MockPortExposer_ExposePorts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPortExposer creates a new instance of MockPortExposer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPortExposer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPortExposer {
	mock := &MockPortExposer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
