// Code generated by mockery v2.20.0. DO NOT EDIT.

package controllers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	networkingv1 "k8s.io/api/networking/v1"

	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/client-go/applyconfigurations/networking/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// mockIngressClassInterface is an autogenerated mock type for the ingressClassInterface type
type mockIngressClassInterface struct {
	mock.Mock
}

type mockIngressClassInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIngressClassInterface) EXPECT() *mockIngressClassInterface_Expecter {
	return &mockIngressClassInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, ingressClass, opts
func (_m *mockIngressClassInterface) Apply(ctx context.Context, ingressClass *v1.IngressClassApplyConfiguration, opts metav1.ApplyOptions) (*networkingv1.IngressClass, error) {
	ret := _m.Called(ctx, ingressClass, opts)

	var r0 *networkingv1.IngressClass
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.IngressClassApplyConfiguration, metav1.ApplyOptions) (*networkingv1.IngressClass, error)); ok {
		return rf(ctx, ingressClass, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.IngressClassApplyConfiguration, metav1.ApplyOptions) *networkingv1.IngressClass); ok {
		r0 = rf(ctx, ingressClass, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.IngressClass)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.IngressClassApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, ingressClass, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressClassInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type mockIngressClassInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - ingressClass *v1.IngressClassApplyConfiguration
//   - opts metav1.ApplyOptions
func (_e *mockIngressClassInterface_Expecter) Apply(ctx interface{}, ingressClass interface{}, opts interface{}) *mockIngressClassInterface_Apply_Call {
	return &mockIngressClassInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, ingressClass, opts)}
}

func (_c *mockIngressClassInterface_Apply_Call) Run(run func(ctx context.Context, ingressClass *v1.IngressClassApplyConfiguration, opts metav1.ApplyOptions)) *mockIngressClassInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.IngressClassApplyConfiguration), args[2].(metav1.ApplyOptions))
	})
	return _c
}

func (_c *mockIngressClassInterface_Apply_Call) Return(result *networkingv1.IngressClass, err error) *mockIngressClassInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockIngressClassInterface_Apply_Call) RunAndReturn(run func(context.Context, *v1.IngressClassApplyConfiguration, metav1.ApplyOptions) (*networkingv1.IngressClass, error)) *mockIngressClassInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, ingressClass, opts
func (_m *mockIngressClassInterface) Create(ctx context.Context, ingressClass *networkingv1.IngressClass, opts metav1.CreateOptions) (*networkingv1.IngressClass, error) {
	ret := _m.Called(ctx, ingressClass, opts)

	var r0 *networkingv1.IngressClass
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *networkingv1.IngressClass, metav1.CreateOptions) (*networkingv1.IngressClass, error)); ok {
		return rf(ctx, ingressClass, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *networkingv1.IngressClass, metav1.CreateOptions) *networkingv1.IngressClass); ok {
		r0 = rf(ctx, ingressClass, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.IngressClass)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *networkingv1.IngressClass, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, ingressClass, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressClassInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockIngressClassInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ingressClass *networkingv1.IngressClass
//   - opts metav1.CreateOptions
func (_e *mockIngressClassInterface_Expecter) Create(ctx interface{}, ingressClass interface{}, opts interface{}) *mockIngressClassInterface_Create_Call {
	return &mockIngressClassInterface_Create_Call{Call: _e.mock.On("Create", ctx, ingressClass, opts)}
}

func (_c *mockIngressClassInterface_Create_Call) Run(run func(ctx context.Context, ingressClass *networkingv1.IngressClass, opts metav1.CreateOptions)) *mockIngressClassInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*networkingv1.IngressClass), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *mockIngressClassInterface_Create_Call) Return(_a0 *networkingv1.IngressClass, _a1 error) *mockIngressClassInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressClassInterface_Create_Call) RunAndReturn(run func(context.Context, *networkingv1.IngressClass, metav1.CreateOptions) (*networkingv1.IngressClass, error)) *mockIngressClassInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *mockIngressClassInterface) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockIngressClassInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockIngressClassInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *mockIngressClassInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *mockIngressClassInterface_Delete_Call {
	return &mockIngressClassInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockIngressClassInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *mockIngressClassInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *mockIngressClassInterface_Delete_Call) Return(_a0 error) *mockIngressClassInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIngressClassInterface_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *mockIngressClassInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *mockIngressClassInterface) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockIngressClassInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type mockIngressClassInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.DeleteOptions
//   - listOpts metav1.ListOptions
func (_e *mockIngressClassInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *mockIngressClassInterface_DeleteCollection_Call {
	return &mockIngressClassInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *mockIngressClassInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions)) *mockIngressClassInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.DeleteOptions), args[2].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockIngressClassInterface_DeleteCollection_Call) Return(_a0 error) *mockIngressClassInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIngressClassInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error) *mockIngressClassInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockIngressClassInterface) Get(ctx context.Context, name string, opts metav1.GetOptions) (*networkingv1.IngressClass, error) {
	ret := _m.Called(ctx, name, opts)

	var r0 *networkingv1.IngressClass
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*networkingv1.IngressClass, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *networkingv1.IngressClass); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.IngressClass)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressClassInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockIngressClassInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *mockIngressClassInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockIngressClassInterface_Get_Call {
	return &mockIngressClassInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockIngressClassInterface_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *mockIngressClassInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *mockIngressClassInterface_Get_Call) Return(_a0 *networkingv1.IngressClass, _a1 error) *mockIngressClassInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressClassInterface_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*networkingv1.IngressClass, error)) *mockIngressClassInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *mockIngressClassInterface) List(ctx context.Context, opts metav1.ListOptions) (*networkingv1.IngressClassList, error) {
	ret := _m.Called(ctx, opts)

	var r0 *networkingv1.IngressClassList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (*networkingv1.IngressClassList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *networkingv1.IngressClassList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.IngressClassList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressClassInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockIngressClassInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockIngressClassInterface_Expecter) List(ctx interface{}, opts interface{}) *mockIngressClassInterface_List_Call {
	return &mockIngressClassInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *mockIngressClassInterface_List_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockIngressClassInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockIngressClassInterface_List_Call) Return(_a0 *networkingv1.IngressClassList, _a1 error) *mockIngressClassInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressClassInterface_List_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (*networkingv1.IngressClassList, error)) *mockIngressClassInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *mockIngressClassInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*networkingv1.IngressClass, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *networkingv1.IngressClass
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*networkingv1.IngressClass, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) *networkingv1.IngressClass); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.IngressClass)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressClassInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type mockIngressClassInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts metav1.PatchOptions
//   - subresources ...string
func (_e *mockIngressClassInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *mockIngressClassInterface_Patch_Call {
	return &mockIngressClassInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *mockIngressClassInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string)) *mockIngressClassInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(metav1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *mockIngressClassInterface_Patch_Call) Return(result *networkingv1.IngressClass, err error) *mockIngressClassInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockIngressClassInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*networkingv1.IngressClass, error)) *mockIngressClassInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, ingressClass, opts
func (_m *mockIngressClassInterface) Update(ctx context.Context, ingressClass *networkingv1.IngressClass, opts metav1.UpdateOptions) (*networkingv1.IngressClass, error) {
	ret := _m.Called(ctx, ingressClass, opts)

	var r0 *networkingv1.IngressClass
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *networkingv1.IngressClass, metav1.UpdateOptions) (*networkingv1.IngressClass, error)); ok {
		return rf(ctx, ingressClass, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *networkingv1.IngressClass, metav1.UpdateOptions) *networkingv1.IngressClass); ok {
		r0 = rf(ctx, ingressClass, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.IngressClass)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *networkingv1.IngressClass, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, ingressClass, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressClassInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockIngressClassInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ingressClass *networkingv1.IngressClass
//   - opts metav1.UpdateOptions
func (_e *mockIngressClassInterface_Expecter) Update(ctx interface{}, ingressClass interface{}, opts interface{}) *mockIngressClassInterface_Update_Call {
	return &mockIngressClassInterface_Update_Call{Call: _e.mock.On("Update", ctx, ingressClass, opts)}
}

func (_c *mockIngressClassInterface_Update_Call) Run(run func(ctx context.Context, ingressClass *networkingv1.IngressClass, opts metav1.UpdateOptions)) *mockIngressClassInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*networkingv1.IngressClass), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockIngressClassInterface_Update_Call) Return(_a0 *networkingv1.IngressClass, _a1 error) *mockIngressClassInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressClassInterface_Update_Call) RunAndReturn(run func(context.Context, *networkingv1.IngressClass, metav1.UpdateOptions) (*networkingv1.IngressClass, error)) *mockIngressClassInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *mockIngressClassInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressClassInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type mockIngressClassInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockIngressClassInterface_Expecter) Watch(ctx interface{}, opts interface{}) *mockIngressClassInterface_Watch_Call {
	return &mockIngressClassInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *mockIngressClassInterface_Watch_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockIngressClassInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockIngressClassInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *mockIngressClassInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressClassInterface_Watch_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (watch.Interface, error)) *mockIngressClassInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockIngressClassInterface interface {
	mock.TestingT
	Cleanup(func())
}

// newMockIngressClassInterface creates a new instance of mockIngressClassInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockIngressClassInterface(t mockConstructorTestingTnewMockIngressClassInterface) *mockIngressClassInterface {
	mock := &mockIngressClassInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
