// Code generated by mockery v2.52.4. DO NOT EDIT.

package controllers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/core/v1"
)

// MockIngressUpdater is an autogenerated mock type for the IngressUpdater type
type MockIngressUpdater struct {
	mock.Mock
}

type MockIngressUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngressUpdater) EXPECT() *MockIngressUpdater_Expecter {
	return &MockIngressUpdater_Expecter{mock: &_m.Mock}
}

// UpsertIngressForService provides a mock function with given fields: ctx, service
func (_m *MockIngressUpdater) UpsertIngressForService(ctx context.Context, service *v1.Service) error {
	ret := _m.Called(ctx, service)

	if len(ret) == 0 {
		panic("no return value specified for UpsertIngressForService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Service) error); ok {
		r0 = rf(ctx, service)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIngressUpdater_UpsertIngressForService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertIngressForService'
type MockIngressUpdater_UpsertIngressForService_Call struct {
	*mock.Call
}

// UpsertIngressForService is a helper method to define mock.On call
//   - ctx context.Context
//   - service *v1.Service
func (_e *MockIngressUpdater_Expecter) UpsertIngressForService(ctx interface{}, service interface{}) *MockIngressUpdater_UpsertIngressForService_Call {
	return &MockIngressUpdater_UpsertIngressForService_Call{Call: _e.mock.On("UpsertIngressForService", ctx, service)}
}

func (_c *MockIngressUpdater_UpsertIngressForService_Call) Run(run func(ctx context.Context, service *v1.Service)) *MockIngressUpdater_UpsertIngressForService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Service))
	})
	return _c
}

func (_c *MockIngressUpdater_UpsertIngressForService_Call) Return(_a0 error) *MockIngressUpdater_UpsertIngressForService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIngressUpdater_UpsertIngressForService_Call) RunAndReturn(run func(context.Context, *v1.Service) error) *MockIngressUpdater_UpsertIngressForService_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIngressUpdater creates a new instance of MockIngressUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngressUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngressUpdater {
	mock := &MockIngressUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
