// Code generated by mockery v2.53.6. DO NOT EDIT.

package controllers

import (
	types "github.com/cloudogu/k8s-service-discovery/v2/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// mockExposedPortGetter is an autogenerated mock type for the exposedPortGetter type
type mockExposedPortGetter struct {
	mock.Mock
}

type mockExposedPortGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockExposedPortGetter) EXPECT() *mockExposedPortGetter_Expecter {
	return &mockExposedPortGetter_Expecter{mock: &_m.Mock}
}

// GetExposedPorts provides a mock function with no fields
func (_m *mockExposedPortGetter) GetExposedPorts() (types.ExposedPorts, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExposedPorts")
	}

	var r0 types.ExposedPorts
	var r1 error
	if rf, ok := ret.Get(0).(func() (types.ExposedPorts, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() types.ExposedPorts); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.ExposedPorts)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExposedPortGetter_GetExposedPorts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExposedPorts'
type mockExposedPortGetter_GetExposedPorts_Call struct {
	*mock.Call
}

// GetExposedPorts is a helper method to define mock.On call
func (_e *mockExposedPortGetter_Expecter) GetExposedPorts() *mockExposedPortGetter_GetExposedPorts_Call {
	return &mockExposedPortGetter_GetExposedPorts_Call{Call: _e.mock.On("GetExposedPorts")}
}

func (_c *mockExposedPortGetter_GetExposedPorts_Call) Run(run func()) *mockExposedPortGetter_GetExposedPorts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockExposedPortGetter_GetExposedPorts_Call) Return(_a0 types.ExposedPorts, _a1 error) *mockExposedPortGetter_GetExposedPorts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockExposedPortGetter_GetExposedPorts_Call) RunAndReturn(run func() (types.ExposedPorts, error)) *mockExposedPortGetter_GetExposedPorts_Call {
	_c.Call.Return(run)
	return _c
}

// newMockExposedPortGetter creates a new instance of mockExposedPortGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockExposedPortGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockExposedPortGetter {
	mock := &mockExposedPortGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
