// Code generated by mockery v2.53.5. DO NOT EDIT.

package controllers

import (
	context "context"

	types "github.com/cloudogu/k8s-service-discovery/v2/internal/types"
	mock "github.com/stretchr/testify/mock"

	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockExpositionService is an autogenerated mock type for the ExpositionService type
type MockExpositionService struct {
	mock.Mock
}

type MockExpositionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpositionService) EXPECT() *MockExpositionService_Expecter {
	return &MockExpositionService_Expecter{mock: &_m.Mock}
}

// GetOwnableTypes provides a mock function with no fields
func (_m *MockExpositionService) GetOwnableTypes() []client.Object {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOwnableTypes")
	}

	var r0 []client.Object
	if rf, ok := ret.Get(0).(func() []client.Object); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Object)
		}
	}

	return r0
}

// MockExpositionService_GetOwnableTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOwnableTypes'
type MockExpositionService_GetOwnableTypes_Call struct {
	*mock.Call
}

// GetOwnableTypes is a helper method to define mock.On call
func (_e *MockExpositionService_Expecter) GetOwnableTypes() *MockExpositionService_GetOwnableTypes_Call {
	return &MockExpositionService_GetOwnableTypes_Call{Call: _e.mock.On("GetOwnableTypes")}
}

func (_c *MockExpositionService_GetOwnableTypes_Call) Run(run func()) *MockExpositionService_GetOwnableTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExpositionService_GetOwnableTypes_Call) Return(_a0 []client.Object) *MockExpositionService_GetOwnableTypes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpositionService_GetOwnableTypes_Call) RunAndReturn(run func() []client.Object) *MockExpositionService_GetOwnableTypes_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessExposition provides a mock function with given fields: ctx, exposition
func (_m *MockExpositionService) ProcessExposition(ctx context.Context, exposition types.Exposition) error {
	ret := _m.Called(ctx, exposition)

	if len(ret) == 0 {
		panic("no return value specified for ProcessExposition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Exposition) error); ok {
		r0 = rf(ctx, exposition)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpositionService_ProcessExposition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessExposition'
type MockExpositionService_ProcessExposition_Call struct {
	*mock.Call
}

// ProcessExposition is a helper method to define mock.On call
//   - ctx context.Context
//   - exposition types.Exposition
func (_e *MockExpositionService_Expecter) ProcessExposition(ctx interface{}, exposition interface{}) *MockExpositionService_ProcessExposition_Call {
	return &MockExpositionService_ProcessExposition_Call{Call: _e.mock.On("ProcessExposition", ctx, exposition)}
}

func (_c *MockExpositionService_ProcessExposition_Call) Run(run func(ctx context.Context, exposition types.Exposition)) *MockExpositionService_ProcessExposition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.Exposition))
	})
	return _c
}

func (_c *MockExpositionService_ProcessExposition_Call) Return(_a0 error) *MockExpositionService_ProcessExposition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpositionService_ProcessExposition_Call) RunAndReturn(run func(context.Context, types.Exposition) error) *MockExpositionService_ProcessExposition_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExpositionService creates a new instance of MockExpositionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpositionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpositionService {
	mock := &MockExpositionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
