apiVersion: v1
kind: Service
metadata:
  labels:
    app: ces
    app.kubernetes.io/name: k8s-service-discovery
    control-plane: controller-manager
  name: controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
