---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
  labels:
    app: ces
    app.kubernetes.io/name: k8s-service-discovery
rules:
  # We need to check whether the ingress class for the ingress objects exists. If not, we need to create it.
  - apiGroups:
      - "*"
    resources:
      - ingressclasses
    verbs:
      - get
      - create
      - list
      - watch