---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
rules:
  - apiGroups:
      - "*"
    resources:
      - ingresses
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - update
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs:
      - list
      - watch
      - get
      - delete
  - apiGroups:
      - "*"
    resources:
      - deployments
      - services
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - "*"
    resources:
      - secrets
    verbs:
      - list
      - watch
      - get
      - create
      - delete
  - apiGroups:
      - "k8s.cloudogu.com"
    resources:
      - dogus
    verbs:
      - watch
      - list
