#
# The default configuration map for the warp menu.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-ces-warp-config
  labels:
    app: ces
    app.kubernetes.io/name: k8s-service-discovery
data:
  warp: |
    sources:
      - path: /dogu
        type: dogus
        tag: warp
      - path: /config/nginx/externals
        type: externals
      - path: /config/_global/block_warpmenu_support_category
        type: support_entry_config
      - path: /config/_global/allowed_warpmenu_support_entries
        type: support_entry_config
      - path: /config/_global/disabled_warpmenu_support_entries
        type: support_entry_config
    target: /var/www/html/warp/menu.json
    order:
      Development Apps: 100
    support:
      - identifier: docsCloudoguComUrl
        external: true
        href: https://docs.cloudogu.com/
      - identifier: aboutCloudoguToken
        external: false
        href: /info/about
      - identifier: platform
        external: true
        href: https://platform.cloudogu.com
