// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	config "github.com/cloudogu/k8s-service-discovery/controllers/config"
	mock "github.com/stretchr/testify/mock"

	types "github.com/cloudogu/k8s-service-discovery/controllers/warp/types"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// read provides a mock function with given fields: configuration
func (_m *Reader) Read(configuration *config.Configuration) (types.Categories, error) {
	ret := _m.Called(configuration)

	var r0 types.Categories
	if rf, ok := ret.Get(0).(func(*config.Configuration) types.Categories); ok {
		r0 = rf(configuration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Categories)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*config.Configuration) error); ok {
		r1 = rf(configuration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
