apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-service-discovery.name" . }}-certificate-role
  labels:
  {{- include "k8s-service-discovery.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - "global-config"
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      -  "ecosystem-certificate"
    verbs:
      - get
      - create
      - update