apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-service-discovery.name" . }}-ces-warp-config
  labels:
  {{- include "k8s-service-discovery.labels" . | nindent 4 }}
data:
  warp: {{ .Values.cesWarpConfig.warp | quote }}