apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-service-discovery.name" . }}-ces-menu-json
  labels:
  {{- include "k8s-service-discovery.labels" . | nindent 4 }}
data:
  menu.json: |-
    [

    ]