{{- if .Values.global.networkPolicies.enabled and .Values.global.networkPolicies.denyAll }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: '{{ .Release.Namespace }}-deny-all-ingress'
  namespace: '{{ .Release.Namespace }}'
spec:
  podSelector: {}
  policyTypes:
    - Ingress
{{- end }}