# Role Definition: Event-recorder enables the operator to create events for the current deployment

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-service-discovery.name" . }}-event-recorder-role
  labels:
  {{- include "k8s-service-discovery.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    resourceNames:
      - "k8s-service-discovery-controller-manager"
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch