apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-service-discovery.name" . }}-maintenance-mode-role
  labels:
  {{- include "k8s-service-discovery.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - "global-config"
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - update
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - dogus
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - ingresses
    verbs:
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - delete