apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-service-discovery.name" . }}-manager-config
  labels:
  {{- include "k8s-service-discovery.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    health:
      healthProbeBindAddress: ":8081"
    kind: ControllerManagerConfig
    leaderElection:
      leaderElect: true
      resourceName: 92a787f2.cloudogu.com
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443