apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-service-discovery.name" . }}-proxy-role
  labels:
  {{- include "k8s-service-discovery.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-service-discovery.name" . }}-proxy-rolebinding
  labels:
  {{- include "k8s-service-discovery.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "k8s-service-discovery.name" . }}-proxy-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "k8s-service-discovery.name" . }}-sa'
  namespace: '{{ .Release.Namespace }}'