// Code generated by mockery v2.53.3. DO NOT EDIT.

package traefik

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1alpha1 "github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/generated/applyconfiguration/traefikio/v1alpha1"
	traefikiov1alpha1 "github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/traefikio/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
)

// mockIngressrouteUdpInterface is an autogenerated mock type for the ingressrouteUdpInterface type
type mockIngressrouteUdpInterface struct {
	mock.Mock
}

type mockIngressrouteUdpInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIngressrouteUdpInterface) EXPECT() *mockIngressrouteUdpInterface_Expecter {
	return &mockIngressrouteUdpInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, ingressRouteUDP, opts
func (_m *mockIngressrouteUdpInterface) Apply(ctx context.Context, ingressRouteUDP *v1alpha1.IngressRouteUDPApplyConfiguration, opts v1.ApplyOptions) (*traefikiov1alpha1.IngressRouteUDP, error) {
	ret := _m.Called(ctx, ingressRouteUDP, opts)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *traefikiov1alpha1.IngressRouteUDP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.IngressRouteUDPApplyConfiguration, v1.ApplyOptions) (*traefikiov1alpha1.IngressRouteUDP, error)); ok {
		return rf(ctx, ingressRouteUDP, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.IngressRouteUDPApplyConfiguration, v1.ApplyOptions) *traefikiov1alpha1.IngressRouteUDP); ok {
		r0 = rf(ctx, ingressRouteUDP, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefikiov1alpha1.IngressRouteUDP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.IngressRouteUDPApplyConfiguration, v1.ApplyOptions) error); ok {
		r1 = rf(ctx, ingressRouteUDP, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressrouteUdpInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type mockIngressrouteUdpInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - ingressRouteUDP *v1alpha1.IngressRouteUDPApplyConfiguration
//   - opts v1.ApplyOptions
func (_e *mockIngressrouteUdpInterface_Expecter) Apply(ctx interface{}, ingressRouteUDP interface{}, opts interface{}) *mockIngressrouteUdpInterface_Apply_Call {
	return &mockIngressrouteUdpInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, ingressRouteUDP, opts)}
}

func (_c *mockIngressrouteUdpInterface_Apply_Call) Run(run func(ctx context.Context, ingressRouteUDP *v1alpha1.IngressRouteUDPApplyConfiguration, opts v1.ApplyOptions)) *mockIngressrouteUdpInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.IngressRouteUDPApplyConfiguration), args[2].(v1.ApplyOptions))
	})
	return _c
}

func (_c *mockIngressrouteUdpInterface_Apply_Call) Return(result *traefikiov1alpha1.IngressRouteUDP, err error) *mockIngressrouteUdpInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockIngressrouteUdpInterface_Apply_Call) RunAndReturn(run func(context.Context, *v1alpha1.IngressRouteUDPApplyConfiguration, v1.ApplyOptions) (*traefikiov1alpha1.IngressRouteUDP, error)) *mockIngressrouteUdpInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, ingressRouteUDP, opts
func (_m *mockIngressrouteUdpInterface) Create(ctx context.Context, ingressRouteUDP *traefikiov1alpha1.IngressRouteUDP, opts v1.CreateOptions) (*traefikiov1alpha1.IngressRouteUDP, error) {
	ret := _m.Called(ctx, ingressRouteUDP, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *traefikiov1alpha1.IngressRouteUDP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *traefikiov1alpha1.IngressRouteUDP, v1.CreateOptions) (*traefikiov1alpha1.IngressRouteUDP, error)); ok {
		return rf(ctx, ingressRouteUDP, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *traefikiov1alpha1.IngressRouteUDP, v1.CreateOptions) *traefikiov1alpha1.IngressRouteUDP); ok {
		r0 = rf(ctx, ingressRouteUDP, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefikiov1alpha1.IngressRouteUDP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *traefikiov1alpha1.IngressRouteUDP, v1.CreateOptions) error); ok {
		r1 = rf(ctx, ingressRouteUDP, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressrouteUdpInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockIngressrouteUdpInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ingressRouteUDP *traefikiov1alpha1.IngressRouteUDP
//   - opts v1.CreateOptions
func (_e *mockIngressrouteUdpInterface_Expecter) Create(ctx interface{}, ingressRouteUDP interface{}, opts interface{}) *mockIngressrouteUdpInterface_Create_Call {
	return &mockIngressrouteUdpInterface_Create_Call{Call: _e.mock.On("Create", ctx, ingressRouteUDP, opts)}
}

func (_c *mockIngressrouteUdpInterface_Create_Call) Run(run func(ctx context.Context, ingressRouteUDP *traefikiov1alpha1.IngressRouteUDP, opts v1.CreateOptions)) *mockIngressrouteUdpInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*traefikiov1alpha1.IngressRouteUDP), args[2].(v1.CreateOptions))
	})
	return _c
}

func (_c *mockIngressrouteUdpInterface_Create_Call) Return(_a0 *traefikiov1alpha1.IngressRouteUDP, _a1 error) *mockIngressrouteUdpInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressrouteUdpInterface_Create_Call) RunAndReturn(run func(context.Context, *traefikiov1alpha1.IngressRouteUDP, v1.CreateOptions) (*traefikiov1alpha1.IngressRouteUDP, error)) *mockIngressrouteUdpInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *mockIngressrouteUdpInterface) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockIngressrouteUdpInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockIngressrouteUdpInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.DeleteOptions
func (_e *mockIngressrouteUdpInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *mockIngressrouteUdpInterface_Delete_Call {
	return &mockIngressrouteUdpInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockIngressrouteUdpInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts v1.DeleteOptions)) *mockIngressrouteUdpInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.DeleteOptions))
	})
	return _c
}

func (_c *mockIngressrouteUdpInterface_Delete_Call) Return(_a0 error) *mockIngressrouteUdpInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIngressrouteUdpInterface_Delete_Call) RunAndReturn(run func(context.Context, string, v1.DeleteOptions) error) *mockIngressrouteUdpInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *mockIngressrouteUdpInterface) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.DeleteOptions, v1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockIngressrouteUdpInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type mockIngressrouteUdpInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.DeleteOptions
//   - listOpts v1.ListOptions
func (_e *mockIngressrouteUdpInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *mockIngressrouteUdpInterface_DeleteCollection_Call {
	return &mockIngressrouteUdpInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *mockIngressrouteUdpInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions)) *mockIngressrouteUdpInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.DeleteOptions), args[2].(v1.ListOptions))
	})
	return _c
}

func (_c *mockIngressrouteUdpInterface_DeleteCollection_Call) Return(_a0 error) *mockIngressrouteUdpInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIngressrouteUdpInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, v1.DeleteOptions, v1.ListOptions) error) *mockIngressrouteUdpInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockIngressrouteUdpInterface) Get(ctx context.Context, name string, opts v1.GetOptions) (*traefikiov1alpha1.IngressRouteUDP, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *traefikiov1alpha1.IngressRouteUDP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*traefikiov1alpha1.IngressRouteUDP, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *traefikiov1alpha1.IngressRouteUDP); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefikiov1alpha1.IngressRouteUDP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressrouteUdpInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockIngressrouteUdpInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *mockIngressrouteUdpInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockIngressrouteUdpInterface_Get_Call {
	return &mockIngressrouteUdpInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockIngressrouteUdpInterface_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *mockIngressrouteUdpInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *mockIngressrouteUdpInterface_Get_Call) Return(_a0 *traefikiov1alpha1.IngressRouteUDP, _a1 error) *mockIngressrouteUdpInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressrouteUdpInterface_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*traefikiov1alpha1.IngressRouteUDP, error)) *mockIngressrouteUdpInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *mockIngressrouteUdpInterface) List(ctx context.Context, opts v1.ListOptions) (*traefikiov1alpha1.IngressRouteUDPList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *traefikiov1alpha1.IngressRouteUDPList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*traefikiov1alpha1.IngressRouteUDPList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *traefikiov1alpha1.IngressRouteUDPList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefikiov1alpha1.IngressRouteUDPList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressrouteUdpInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockIngressrouteUdpInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *mockIngressrouteUdpInterface_Expecter) List(ctx interface{}, opts interface{}) *mockIngressrouteUdpInterface_List_Call {
	return &mockIngressrouteUdpInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *mockIngressrouteUdpInterface_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *mockIngressrouteUdpInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *mockIngressrouteUdpInterface_List_Call) Return(_a0 *traefikiov1alpha1.IngressRouteUDPList, _a1 error) *mockIngressrouteUdpInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressrouteUdpInterface_List_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (*traefikiov1alpha1.IngressRouteUDPList, error)) *mockIngressrouteUdpInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *mockIngressrouteUdpInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (*traefikiov1alpha1.IngressRouteUDP, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *traefikiov1alpha1.IngressRouteUDP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*traefikiov1alpha1.IngressRouteUDP, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) *traefikiov1alpha1.IngressRouteUDP); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefikiov1alpha1.IngressRouteUDP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressrouteUdpInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type mockIngressrouteUdpInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts v1.PatchOptions
//   - subresources ...string
func (_e *mockIngressrouteUdpInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *mockIngressrouteUdpInterface_Patch_Call {
	return &mockIngressrouteUdpInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *mockIngressrouteUdpInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string)) *mockIngressrouteUdpInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(v1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *mockIngressrouteUdpInterface_Patch_Call) Return(result *traefikiov1alpha1.IngressRouteUDP, err error) *mockIngressrouteUdpInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockIngressrouteUdpInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*traefikiov1alpha1.IngressRouteUDP, error)) *mockIngressrouteUdpInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, ingressRouteUDP, opts
func (_m *mockIngressrouteUdpInterface) Update(ctx context.Context, ingressRouteUDP *traefikiov1alpha1.IngressRouteUDP, opts v1.UpdateOptions) (*traefikiov1alpha1.IngressRouteUDP, error) {
	ret := _m.Called(ctx, ingressRouteUDP, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *traefikiov1alpha1.IngressRouteUDP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *traefikiov1alpha1.IngressRouteUDP, v1.UpdateOptions) (*traefikiov1alpha1.IngressRouteUDP, error)); ok {
		return rf(ctx, ingressRouteUDP, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *traefikiov1alpha1.IngressRouteUDP, v1.UpdateOptions) *traefikiov1alpha1.IngressRouteUDP); ok {
		r0 = rf(ctx, ingressRouteUDP, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefikiov1alpha1.IngressRouteUDP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *traefikiov1alpha1.IngressRouteUDP, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, ingressRouteUDP, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressrouteUdpInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockIngressrouteUdpInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ingressRouteUDP *traefikiov1alpha1.IngressRouteUDP
//   - opts v1.UpdateOptions
func (_e *mockIngressrouteUdpInterface_Expecter) Update(ctx interface{}, ingressRouteUDP interface{}, opts interface{}) *mockIngressrouteUdpInterface_Update_Call {
	return &mockIngressrouteUdpInterface_Update_Call{Call: _e.mock.On("Update", ctx, ingressRouteUDP, opts)}
}

func (_c *mockIngressrouteUdpInterface_Update_Call) Run(run func(ctx context.Context, ingressRouteUDP *traefikiov1alpha1.IngressRouteUDP, opts v1.UpdateOptions)) *mockIngressrouteUdpInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*traefikiov1alpha1.IngressRouteUDP), args[2].(v1.UpdateOptions))
	})
	return _c
}

func (_c *mockIngressrouteUdpInterface_Update_Call) Return(_a0 *traefikiov1alpha1.IngressRouteUDP, _a1 error) *mockIngressrouteUdpInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressrouteUdpInterface_Update_Call) RunAndReturn(run func(context.Context, *traefikiov1alpha1.IngressRouteUDP, v1.UpdateOptions) (*traefikiov1alpha1.IngressRouteUDP, error)) *mockIngressrouteUdpInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *mockIngressrouteUdpInterface) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIngressrouteUdpInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type mockIngressrouteUdpInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *mockIngressrouteUdpInterface_Expecter) Watch(ctx interface{}, opts interface{}) *mockIngressrouteUdpInterface_Watch_Call {
	return &mockIngressrouteUdpInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *mockIngressrouteUdpInterface_Watch_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *mockIngressrouteUdpInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *mockIngressrouteUdpInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *mockIngressrouteUdpInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIngressrouteUdpInterface_Watch_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (watch.Interface, error)) *mockIngressrouteUdpInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// newMockIngressrouteUdpInterface creates a new instance of mockIngressrouteUdpInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIngressrouteUdpInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIngressrouteUdpInterface {
	mock := &mockIngressrouteUdpInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
