// Code generated by mockery v2.53.3. DO NOT EDIT.

package traefik

import (
	mock "github.com/stretchr/testify/mock"
	v1alpha1 "github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefikio/v1alpha1"
	rest "k8s.io/client-go/rest"
)

// mockTraefikInterface is an autogenerated mock type for the traefikInterface type
type mockTraefikInterface struct {
	mock.Mock
}

type mockTraefikInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTraefikInterface) EXPECT() *mockTraefikInterface_Expecter {
	return &mockTraefikInterface_Expecter{mock: &_m.Mock}
}

// IngressRouteTCPs provides a mock function with given fields: namespace
func (_m *mockTraefikInterface) IngressRouteTCPs(namespace string) v1alpha1.IngressRouteTCPInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for IngressRouteTCPs")
	}

	var r0 v1alpha1.IngressRouteTCPInterface
	if rf, ok := ret.Get(0).(func(string) v1alpha1.IngressRouteTCPInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.IngressRouteTCPInterface)
		}
	}

	return r0
}

// mockTraefikInterface_IngressRouteTCPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngressRouteTCPs'
type mockTraefikInterface_IngressRouteTCPs_Call struct {
	*mock.Call
}

// IngressRouteTCPs is a helper method to define mock.On call
//   - namespace string
func (_e *mockTraefikInterface_Expecter) IngressRouteTCPs(namespace interface{}) *mockTraefikInterface_IngressRouteTCPs_Call {
	return &mockTraefikInterface_IngressRouteTCPs_Call{Call: _e.mock.On("IngressRouteTCPs", namespace)}
}

func (_c *mockTraefikInterface_IngressRouteTCPs_Call) Run(run func(namespace string)) *mockTraefikInterface_IngressRouteTCPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockTraefikInterface_IngressRouteTCPs_Call) Return(_a0 v1alpha1.IngressRouteTCPInterface) *mockTraefikInterface_IngressRouteTCPs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTraefikInterface_IngressRouteTCPs_Call) RunAndReturn(run func(string) v1alpha1.IngressRouteTCPInterface) *mockTraefikInterface_IngressRouteTCPs_Call {
	_c.Call.Return(run)
	return _c
}

// IngressRouteUDPs provides a mock function with given fields: namespace
func (_m *mockTraefikInterface) IngressRouteUDPs(namespace string) v1alpha1.IngressRouteUDPInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for IngressRouteUDPs")
	}

	var r0 v1alpha1.IngressRouteUDPInterface
	if rf, ok := ret.Get(0).(func(string) v1alpha1.IngressRouteUDPInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.IngressRouteUDPInterface)
		}
	}

	return r0
}

// mockTraefikInterface_IngressRouteUDPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngressRouteUDPs'
type mockTraefikInterface_IngressRouteUDPs_Call struct {
	*mock.Call
}

// IngressRouteUDPs is a helper method to define mock.On call
//   - namespace string
func (_e *mockTraefikInterface_Expecter) IngressRouteUDPs(namespace interface{}) *mockTraefikInterface_IngressRouteUDPs_Call {
	return &mockTraefikInterface_IngressRouteUDPs_Call{Call: _e.mock.On("IngressRouteUDPs", namespace)}
}

func (_c *mockTraefikInterface_IngressRouteUDPs_Call) Run(run func(namespace string)) *mockTraefikInterface_IngressRouteUDPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockTraefikInterface_IngressRouteUDPs_Call) Return(_a0 v1alpha1.IngressRouteUDPInterface) *mockTraefikInterface_IngressRouteUDPs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTraefikInterface_IngressRouteUDPs_Call) RunAndReturn(run func(string) v1alpha1.IngressRouteUDPInterface) *mockTraefikInterface_IngressRouteUDPs_Call {
	_c.Call.Return(run)
	return _c
}

// IngressRoutes provides a mock function with given fields: namespace
func (_m *mockTraefikInterface) IngressRoutes(namespace string) v1alpha1.IngressRouteInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for IngressRoutes")
	}

	var r0 v1alpha1.IngressRouteInterface
	if rf, ok := ret.Get(0).(func(string) v1alpha1.IngressRouteInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.IngressRouteInterface)
		}
	}

	return r0
}

// mockTraefikInterface_IngressRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngressRoutes'
type mockTraefikInterface_IngressRoutes_Call struct {
	*mock.Call
}

// IngressRoutes is a helper method to define mock.On call
//   - namespace string
func (_e *mockTraefikInterface_Expecter) IngressRoutes(namespace interface{}) *mockTraefikInterface_IngressRoutes_Call {
	return &mockTraefikInterface_IngressRoutes_Call{Call: _e.mock.On("IngressRoutes", namespace)}
}

func (_c *mockTraefikInterface_IngressRoutes_Call) Run(run func(namespace string)) *mockTraefikInterface_IngressRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockTraefikInterface_IngressRoutes_Call) Return(_a0 v1alpha1.IngressRouteInterface) *mockTraefikInterface_IngressRoutes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTraefikInterface_IngressRoutes_Call) RunAndReturn(run func(string) v1alpha1.IngressRouteInterface) *mockTraefikInterface_IngressRoutes_Call {
	_c.Call.Return(run)
	return _c
}

// MiddlewareTCPs provides a mock function with given fields: namespace
func (_m *mockTraefikInterface) MiddlewareTCPs(namespace string) v1alpha1.MiddlewareTCPInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for MiddlewareTCPs")
	}

	var r0 v1alpha1.MiddlewareTCPInterface
	if rf, ok := ret.Get(0).(func(string) v1alpha1.MiddlewareTCPInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.MiddlewareTCPInterface)
		}
	}

	return r0
}

// mockTraefikInterface_MiddlewareTCPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MiddlewareTCPs'
type mockTraefikInterface_MiddlewareTCPs_Call struct {
	*mock.Call
}

// MiddlewareTCPs is a helper method to define mock.On call
//   - namespace string
func (_e *mockTraefikInterface_Expecter) MiddlewareTCPs(namespace interface{}) *mockTraefikInterface_MiddlewareTCPs_Call {
	return &mockTraefikInterface_MiddlewareTCPs_Call{Call: _e.mock.On("MiddlewareTCPs", namespace)}
}

func (_c *mockTraefikInterface_MiddlewareTCPs_Call) Run(run func(namespace string)) *mockTraefikInterface_MiddlewareTCPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockTraefikInterface_MiddlewareTCPs_Call) Return(_a0 v1alpha1.MiddlewareTCPInterface) *mockTraefikInterface_MiddlewareTCPs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTraefikInterface_MiddlewareTCPs_Call) RunAndReturn(run func(string) v1alpha1.MiddlewareTCPInterface) *mockTraefikInterface_MiddlewareTCPs_Call {
	_c.Call.Return(run)
	return _c
}

// Middlewares provides a mock function with given fields: namespace
func (_m *mockTraefikInterface) Middlewares(namespace string) v1alpha1.MiddlewareInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Middlewares")
	}

	var r0 v1alpha1.MiddlewareInterface
	if rf, ok := ret.Get(0).(func(string) v1alpha1.MiddlewareInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.MiddlewareInterface)
		}
	}

	return r0
}

// mockTraefikInterface_Middlewares_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Middlewares'
type mockTraefikInterface_Middlewares_Call struct {
	*mock.Call
}

// Middlewares is a helper method to define mock.On call
//   - namespace string
func (_e *mockTraefikInterface_Expecter) Middlewares(namespace interface{}) *mockTraefikInterface_Middlewares_Call {
	return &mockTraefikInterface_Middlewares_Call{Call: _e.mock.On("Middlewares", namespace)}
}

func (_c *mockTraefikInterface_Middlewares_Call) Run(run func(namespace string)) *mockTraefikInterface_Middlewares_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockTraefikInterface_Middlewares_Call) Return(_a0 v1alpha1.MiddlewareInterface) *mockTraefikInterface_Middlewares_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTraefikInterface_Middlewares_Call) RunAndReturn(run func(string) v1alpha1.MiddlewareInterface) *mockTraefikInterface_Middlewares_Call {
	_c.Call.Return(run)
	return _c
}

// RESTClient provides a mock function with no fields
func (_m *mockTraefikInterface) RESTClient() rest.Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RESTClient")
	}

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// mockTraefikInterface_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type mockTraefikInterface_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *mockTraefikInterface_Expecter) RESTClient() *mockTraefikInterface_RESTClient_Call {
	return &mockTraefikInterface_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *mockTraefikInterface_RESTClient_Call) Run(run func()) *mockTraefikInterface_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTraefikInterface_RESTClient_Call) Return(_a0 rest.Interface) *mockTraefikInterface_RESTClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTraefikInterface_RESTClient_Call) RunAndReturn(run func() rest.Interface) *mockTraefikInterface_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

// ServersTransportTCPs provides a mock function with given fields: namespace
func (_m *mockTraefikInterface) ServersTransportTCPs(namespace string) v1alpha1.ServersTransportTCPInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for ServersTransportTCPs")
	}

	var r0 v1alpha1.ServersTransportTCPInterface
	if rf, ok := ret.Get(0).(func(string) v1alpha1.ServersTransportTCPInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.ServersTransportTCPInterface)
		}
	}

	return r0
}

// mockTraefikInterface_ServersTransportTCPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServersTransportTCPs'
type mockTraefikInterface_ServersTransportTCPs_Call struct {
	*mock.Call
}

// ServersTransportTCPs is a helper method to define mock.On call
//   - namespace string
func (_e *mockTraefikInterface_Expecter) ServersTransportTCPs(namespace interface{}) *mockTraefikInterface_ServersTransportTCPs_Call {
	return &mockTraefikInterface_ServersTransportTCPs_Call{Call: _e.mock.On("ServersTransportTCPs", namespace)}
}

func (_c *mockTraefikInterface_ServersTransportTCPs_Call) Run(run func(namespace string)) *mockTraefikInterface_ServersTransportTCPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockTraefikInterface_ServersTransportTCPs_Call) Return(_a0 v1alpha1.ServersTransportTCPInterface) *mockTraefikInterface_ServersTransportTCPs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTraefikInterface_ServersTransportTCPs_Call) RunAndReturn(run func(string) v1alpha1.ServersTransportTCPInterface) *mockTraefikInterface_ServersTransportTCPs_Call {
	_c.Call.Return(run)
	return _c
}

// ServersTransports provides a mock function with given fields: namespace
func (_m *mockTraefikInterface) ServersTransports(namespace string) v1alpha1.ServersTransportInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for ServersTransports")
	}

	var r0 v1alpha1.ServersTransportInterface
	if rf, ok := ret.Get(0).(func(string) v1alpha1.ServersTransportInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.ServersTransportInterface)
		}
	}

	return r0
}

// mockTraefikInterface_ServersTransports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServersTransports'
type mockTraefikInterface_ServersTransports_Call struct {
	*mock.Call
}

// ServersTransports is a helper method to define mock.On call
//   - namespace string
func (_e *mockTraefikInterface_Expecter) ServersTransports(namespace interface{}) *mockTraefikInterface_ServersTransports_Call {
	return &mockTraefikInterface_ServersTransports_Call{Call: _e.mock.On("ServersTransports", namespace)}
}

func (_c *mockTraefikInterface_ServersTransports_Call) Run(run func(namespace string)) *mockTraefikInterface_ServersTransports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockTraefikInterface_ServersTransports_Call) Return(_a0 v1alpha1.ServersTransportInterface) *mockTraefikInterface_ServersTransports_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTraefikInterface_ServersTransports_Call) RunAndReturn(run func(string) v1alpha1.ServersTransportInterface) *mockTraefikInterface_ServersTransports_Call {
	_c.Call.Return(run)
	return _c
}

// TLSOptions provides a mock function with given fields: namespace
func (_m *mockTraefikInterface) TLSOptions(namespace string) v1alpha1.TLSOptionInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for TLSOptions")
	}

	var r0 v1alpha1.TLSOptionInterface
	if rf, ok := ret.Get(0).(func(string) v1alpha1.TLSOptionInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.TLSOptionInterface)
		}
	}

	return r0
}

// mockTraefikInterface_TLSOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLSOptions'
type mockTraefikInterface_TLSOptions_Call struct {
	*mock.Call
}

// TLSOptions is a helper method to define mock.On call
//   - namespace string
func (_e *mockTraefikInterface_Expecter) TLSOptions(namespace interface{}) *mockTraefikInterface_TLSOptions_Call {
	return &mockTraefikInterface_TLSOptions_Call{Call: _e.mock.On("TLSOptions", namespace)}
}

func (_c *mockTraefikInterface_TLSOptions_Call) Run(run func(namespace string)) *mockTraefikInterface_TLSOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockTraefikInterface_TLSOptions_Call) Return(_a0 v1alpha1.TLSOptionInterface) *mockTraefikInterface_TLSOptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTraefikInterface_TLSOptions_Call) RunAndReturn(run func(string) v1alpha1.TLSOptionInterface) *mockTraefikInterface_TLSOptions_Call {
	_c.Call.Return(run)
	return _c
}

// TLSStores provides a mock function with given fields: namespace
func (_m *mockTraefikInterface) TLSStores(namespace string) v1alpha1.TLSStoreInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for TLSStores")
	}

	var r0 v1alpha1.TLSStoreInterface
	if rf, ok := ret.Get(0).(func(string) v1alpha1.TLSStoreInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.TLSStoreInterface)
		}
	}

	return r0
}

// mockTraefikInterface_TLSStores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLSStores'
type mockTraefikInterface_TLSStores_Call struct {
	*mock.Call
}

// TLSStores is a helper method to define mock.On call
//   - namespace string
func (_e *mockTraefikInterface_Expecter) TLSStores(namespace interface{}) *mockTraefikInterface_TLSStores_Call {
	return &mockTraefikInterface_TLSStores_Call{Call: _e.mock.On("TLSStores", namespace)}
}

func (_c *mockTraefikInterface_TLSStores_Call) Run(run func(namespace string)) *mockTraefikInterface_TLSStores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockTraefikInterface_TLSStores_Call) Return(_a0 v1alpha1.TLSStoreInterface) *mockTraefikInterface_TLSStores_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTraefikInterface_TLSStores_Call) RunAndReturn(run func(string) v1alpha1.TLSStoreInterface) *mockTraefikInterface_TLSStores_Call {
	_c.Call.Return(run)
	return _c
}

// TraefikServices provides a mock function with given fields: namespace
func (_m *mockTraefikInterface) TraefikServices(namespace string) v1alpha1.TraefikServiceInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for TraefikServices")
	}

	var r0 v1alpha1.TraefikServiceInterface
	if rf, ok := ret.Get(0).(func(string) v1alpha1.TraefikServiceInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.TraefikServiceInterface)
		}
	}

	return r0
}

// mockTraefikInterface_TraefikServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TraefikServices'
type mockTraefikInterface_TraefikServices_Call struct {
	*mock.Call
}

// TraefikServices is a helper method to define mock.On call
//   - namespace string
func (_e *mockTraefikInterface_Expecter) TraefikServices(namespace interface{}) *mockTraefikInterface_TraefikServices_Call {
	return &mockTraefikInterface_TraefikServices_Call{Call: _e.mock.On("TraefikServices", namespace)}
}

func (_c *mockTraefikInterface_TraefikServices_Call) Run(run func(namespace string)) *mockTraefikInterface_TraefikServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockTraefikInterface_TraefikServices_Call) Return(_a0 v1alpha1.TraefikServiceInterface) *mockTraefikInterface_TraefikServices_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTraefikInterface_TraefikServices_Call) RunAndReturn(run func(string) v1alpha1.TraefikServiceInterface) *mockTraefikInterface_TraefikServices_Call {
	_c.Call.Return(run)
	return _c
}

// newMockTraefikInterface creates a new instance of mockTraefikInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTraefikInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTraefikInterface {
	mock := &mockTraefikInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
