// Code generated by mockery v2.53.3. DO NOT EDIT.

package types

import (
	context "context"

	client "go.etcd.io/etcd/client/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockWatchConfigurationContext is an autogenerated mock type for the WatchConfigurationContext type
type MockWatchConfigurationContext struct {
	mock.Mock
}

type MockWatchConfigurationContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchConfigurationContext) EXPECT() *MockWatchConfigurationContext_Expecter {
	return &MockWatchConfigurationContext_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *MockWatchConfigurationContext) Get(key string) (string, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWatchConfigurationContext_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWatchConfigurationContext_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockWatchConfigurationContext_Expecter) Get(key interface{}) *MockWatchConfigurationContext_Get_Call {
	return &MockWatchConfigurationContext_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockWatchConfigurationContext_Get_Call) Run(run func(key string)) *MockWatchConfigurationContext_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWatchConfigurationContext_Get_Call) Return(_a0 string, _a1 error) *MockWatchConfigurationContext_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWatchConfigurationContext_Get_Call) RunAndReturn(run func(string) (string, error)) *MockWatchConfigurationContext_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildrenPaths provides a mock function with given fields: key
func (_m *MockWatchConfigurationContext) GetChildrenPaths(key string) ([]string, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetChildrenPaths")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWatchConfigurationContext_GetChildrenPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildrenPaths'
type MockWatchConfigurationContext_GetChildrenPaths_Call struct {
	*mock.Call
}

// GetChildrenPaths is a helper method to define mock.On call
//   - key string
func (_e *MockWatchConfigurationContext_Expecter) GetChildrenPaths(key interface{}) *MockWatchConfigurationContext_GetChildrenPaths_Call {
	return &MockWatchConfigurationContext_GetChildrenPaths_Call{Call: _e.mock.On("GetChildrenPaths", key)}
}

func (_c *MockWatchConfigurationContext_GetChildrenPaths_Call) Run(run func(key string)) *MockWatchConfigurationContext_GetChildrenPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWatchConfigurationContext_GetChildrenPaths_Call) Return(_a0 []string, _a1 error) *MockWatchConfigurationContext_GetChildrenPaths_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWatchConfigurationContext_GetChildrenPaths_Call) RunAndReturn(run func(string) ([]string, error)) *MockWatchConfigurationContext_GetChildrenPaths_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, key, recursive, eventChannel
func (_m *MockWatchConfigurationContext) Watch(ctx context.Context, key string, recursive bool, eventChannel chan *client.Response) {
	_m.Called(ctx, key, recursive, eventChannel)
}

// MockWatchConfigurationContext_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockWatchConfigurationContext_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - recursive bool
//   - eventChannel chan *client.Response
func (_e *MockWatchConfigurationContext_Expecter) Watch(ctx interface{}, key interface{}, recursive interface{}, eventChannel interface{}) *MockWatchConfigurationContext_Watch_Call {
	return &MockWatchConfigurationContext_Watch_Call{Call: _e.mock.On("Watch", ctx, key, recursive, eventChannel)}
}

func (_c *MockWatchConfigurationContext_Watch_Call) Run(run func(ctx context.Context, key string, recursive bool, eventChannel chan *client.Response)) *MockWatchConfigurationContext_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool), args[3].(chan *client.Response))
	})
	return _c
}

func (_c *MockWatchConfigurationContext_Watch_Call) Return() *MockWatchConfigurationContext_Watch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWatchConfigurationContext_Watch_Call) RunAndReturn(run func(context.Context, string, bool, chan *client.Response)) *MockWatchConfigurationContext_Watch_Call {
	_c.Run(run)
	return _c
}

// NewMockWatchConfigurationContext creates a new instance of MockWatchConfigurationContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchConfigurationContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchConfigurationContext {
	mock := &MockWatchConfigurationContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
