// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	registry "github.com/cloudogu/cesapp-lib/registry"
	"github.com/cloudogu/k8s-service-discovery/controllers/warp/types"
	mock "github.com/stretchr/testify/mock"
)

// ExternalConverter is an autogenerated mock type for the ExternalConverter type
type ExternalConverter struct {
	mock.Mock
}

// ReadAndUnmarshalExternal provides a mock function with given fields: _a0, key
func (_m *ExternalConverter) ReadAndUnmarshalExternal(_a0 registry.WatchConfigurationContext, key string) (types.EntryWithCategory, error) {
	ret := _m.Called(_a0, key)

	var r0 types.EntryWithCategory
	if rf, ok := ret.Get(0).(func(registry.WatchConfigurationContext, string) types.EntryWithCategory); ok {
		r0 = rf(_a0, key)
	} else {
		r0 = ret.Get(0).(types.EntryWithCategory)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(registry.WatchConfigurationContext, string) error); ok {
		r1 = rf(_a0, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
