// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockDeploymentReadyChecker is an autogenerated mock type for the deploymentReadyChecker type
type mockDeploymentReadyChecker struct {
	mock.Mock
}

type mockDeploymentReadyChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDeploymentReadyChecker) EXPECT() *mockDeploymentReadyChecker_Expecter {
	return &mockDeploymentReadyChecker_Expecter{mock: &_m.Mock}
}

// IsReady provides a mock function with given fields: ctx, deploymentName
func (_m *mockDeploymentReadyChecker) IsReady(ctx context.Context, deploymentName string) (bool, error) {
	ret := _m.Called(ctx, deploymentName)

	if len(ret) == 0 {
		panic("no return value specified for IsReady")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, deploymentName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, deploymentName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deploymentName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDeploymentReadyChecker_IsReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsReady'
type mockDeploymentReadyChecker_IsReady_Call struct {
	*mock.Call
}

// IsReady is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentName string
func (_e *mockDeploymentReadyChecker_Expecter) IsReady(ctx interface{}, deploymentName interface{}) *mockDeploymentReadyChecker_IsReady_Call {
	return &mockDeploymentReadyChecker_IsReady_Call{Call: _e.mock.On("IsReady", ctx, deploymentName)}
}

func (_c *mockDeploymentReadyChecker_IsReady_Call) Run(run func(ctx context.Context, deploymentName string)) *mockDeploymentReadyChecker_IsReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockDeploymentReadyChecker_IsReady_Call) Return(_a0 bool, _a1 error) *mockDeploymentReadyChecker_IsReady_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDeploymentReadyChecker_IsReady_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *mockDeploymentReadyChecker_IsReady_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDeploymentReadyChecker creates a new instance of mockDeploymentReadyChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDeploymentReadyChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDeploymentReadyChecker {
	mock := &mockDeploymentReadyChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
